// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_btn9;
lv_obj_t * uic_btn6;
lv_obj_t * uic_btn5;
lv_obj_t * uic_btn8;
lv_obj_t * uic_btn0;
lv_obj_t * uic_btn7;
lv_obj_t * uic_btn4;
lv_obj_t * uic_btnC;
lv_obj_t * uic_btnE;
lv_obj_t * uic_Pin1;
lv_obj_t * uic_Pin2;
lv_obj_t * uic_Pin3;
lv_obj_t * uic_statusLabel;
lv_obj_t * uic_Pin0;
lv_obj_t * uic_btn3;
lv_obj_t * uic_btn2;
lv_obj_t * uic_btn1;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_btn1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_btn2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_btn3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Pin0 = NULL;
lv_obj_t * ui_statusLabel = NULL;
lv_obj_t * ui_Pin3 = NULL;
lv_obj_t * ui_Pin2 = NULL;
lv_obj_t * ui_Pin1 = NULL;
lv_obj_t * ui_btnE = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_btnC = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_btn4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_btn7 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_btn0 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_btn8 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_btn5 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_btn6 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_btn9 = NULL;
lv_obj_t * ui_Label14 = NULL;
// event funtions
void ui_event_btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

void ui_event_btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

void ui_event_btn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

void ui_event_btnE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enter_btn_pressed(e);
    }
}

void ui_event_btnC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clear_btn_pressed(e);
    }
}

void ui_event_btn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
        (e);
    }
}

void ui_event_btn7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

void ui_event_btn0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

void ui_event_btn8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

void ui_event_btn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

void ui_event_btn6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

void ui_event_btn9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        num_btn_pressed(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn1, 65);
    lv_obj_set_height(ui_btn1, 35);
    lv_obj_set_x(ui_btn1, -90);
    lv_obj_set_y(ui_btn1, -50);
    lv_obj_set_align(ui_btn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn1, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn1, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn1, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_btn1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "1");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn2 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn2, 65);
    lv_obj_set_height(ui_btn2, 35);
    lv_obj_set_x(ui_btn2, -20);
    lv_obj_set_y(ui_btn2, -50);
    lv_obj_set_align(ui_btn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn2, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn2, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn2, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_btn2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "2");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn3 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn3, 65);
    lv_obj_set_height(ui_btn3, 35);
    lv_obj_set_x(ui_btn3, 50);
    lv_obj_set_y(ui_btn3, -50);
    lv_obj_set_align(ui_btn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn3, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn3, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn3, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_btn3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "3");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pin0 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Pin0, 15);
    lv_obj_set_height(ui_Pin0, 15);
    lv_obj_set_x(ui_Pin0, -80);
    lv_obj_set_y(ui_Pin0, -90);
    lv_obj_set_align(ui_Pin0, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Pin0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pin0, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pin0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pin0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pin0, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pin0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pin0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pin0, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pin0, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_statusLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_statusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLabel, 4);
    lv_obj_set_y(ui_statusLabel, -111);
    lv_obj_set_align(ui_statusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusLabel, "Enter Password");
    lv_obj_set_style_text_color(ui_statusLabel, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_statusLabel, lv_color_hex(0xF44336), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_statusLabel, 200, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Pin3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Pin3, 15);
    lv_obj_set_height(ui_Pin3, 15);
    lv_obj_set_x(ui_Pin3, 100);
    lv_obj_set_y(ui_Pin3, -90);
    lv_obj_set_align(ui_Pin3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Pin3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pin3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pin3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pin3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pin3, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pin3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pin3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pin3, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pin3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Pin2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Pin2, 15);
    lv_obj_set_height(ui_Pin2, 15);
    lv_obj_set_x(ui_Pin2, 40);
    lv_obj_set_y(ui_Pin2, -90);
    lv_obj_set_align(ui_Pin2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Pin2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pin2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pin2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pin2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pin2, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pin2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pin2, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pin2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Pin1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Pin1, 15);
    lv_obj_set_height(ui_Pin1, 15);
    lv_obj_set_x(ui_Pin1, -20);
    lv_obj_set_y(ui_Pin1, -90);
    lv_obj_set_align(ui_Pin1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Pin1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Pin1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pin1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pin1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Pin1, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Pin1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pin1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pin1, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pin1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_btnE = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btnE, 43);
    lv_obj_set_height(ui_btnE, 136);
    lv_obj_set_x(ui_btnE, 113);
    lv_obj_set_y(ui_btnE, -1);
    lv_obj_set_align(ui_btnE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnE, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnE, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnE, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnE, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnE, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnE, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_btnE);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, ">");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnC = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btnC, 43);
    lv_obj_set_height(ui_btnC, 34);
    lv_obj_set_x(ui_btnC, 113);
    lv_obj_set_y(ui_btnC, 100);
    lv_obj_set_align(ui_btnC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnC, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnC, lv_color_hex(0xF44336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnC, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnC, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnC, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnC, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_btnC);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "C");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn4 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn4, 65);
    lv_obj_set_height(ui_btn4, 34);
    lv_obj_set_x(ui_btn4, -90);
    lv_obj_set_y(ui_btn4, 0);
    lv_obj_set_align(ui_btn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn4, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn4, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn4, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_btn4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -1);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "4");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn7 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn7, 65);
    lv_obj_set_height(ui_btn7, 35);
    lv_obj_set_x(ui_btn7, -90);
    lv_obj_set_y(ui_btn7, 50);
    lv_obj_set_align(ui_btn7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn7, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn7, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn7, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_btn7);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -1);
    lv_obj_set_y(ui_Label9, 0);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "7");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn0 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn0, 65);
    lv_obj_set_height(ui_btn0, 35);
    lv_obj_set_x(ui_btn0, -20);
    lv_obj_set_y(ui_btn0, 100);
    lv_obj_set_align(ui_btn0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn0, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn0, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn0, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn0, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn0, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_btn0);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -1);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "0");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn8 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn8, 65);
    lv_obj_set_height(ui_btn8, 35);
    lv_obj_set_x(ui_btn8, -20);
    lv_obj_set_y(ui_btn8, 50);
    lv_obj_set_align(ui_btn8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn8, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn8, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn8, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_btn8);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -1);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "8");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn5 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn5, 65);
    lv_obj_set_height(ui_btn5, 35);
    lv_obj_set_x(ui_btn5, -20);
    lv_obj_set_y(ui_btn5, 0);
    lv_obj_set_align(ui_btn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn5, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn5, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn5, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_btn5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -1);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "5");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn6 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn6, 65);
    lv_obj_set_height(ui_btn6, 35);
    lv_obj_set_x(ui_btn6, 50);
    lv_obj_set_y(ui_btn6, 0);
    lv_obj_set_align(ui_btn6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn6, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn6, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn6, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_btn6);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -1);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "6");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn9 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_btn9, 65);
    lv_obj_set_height(ui_btn9, 35);
    lv_obj_set_x(ui_btn9, 50);
    lv_obj_set_y(ui_btn9, 50);
    lv_obj_set_align(ui_btn9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn9, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn9, lv_color_hex(0x334155), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn9, lv_color_hex(0x475569), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btn9, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_btn9);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -1);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "9");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btn1, ui_event_btn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn2, ui_event_btn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn3, ui_event_btn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnE, ui_event_btnE, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnC, ui_event_btnC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn4, ui_event_btn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn7, ui_event_btn7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn0, ui_event_btn0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn8, ui_event_btn8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn5, ui_event_btn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn6, ui_event_btn6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn9, ui_event_btn9, LV_EVENT_ALL, NULL);
    uic_btn1 = ui_btn1;
    uic_btn2 = ui_btn2;
    uic_btn3 = ui_btn3;
    uic_Pin0 = ui_Pin0;
    uic_statusLabel = ui_statusLabel;
    uic_Pin3 = ui_Pin3;
    uic_Pin2 = ui_Pin2;
    uic_Pin1 = ui_Pin1;
    uic_btnE = ui_btnE;
    uic_btnC = ui_btnC;
    uic_btn4 = ui_btn4;
    uic_btn7 = ui_btn7;
    uic_btn0 = ui_btn0;
    uic_btn8 = ui_btn8;
    uic_btn5 = ui_btn5;
    uic_btn6 = ui_btn6;
    uic_btn9 = ui_btn9;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    uic_btn1 = NULL;
    ui_btn1 = NULL;
    ui_Label3 = NULL;
    uic_btn2 = NULL;
    ui_btn2 = NULL;
    ui_Label4 = NULL;
    uic_btn3 = NULL;
    ui_btn3 = NULL;
    ui_Label5 = NULL;
    uic_Pin0 = NULL;
    ui_Pin0 = NULL;
    uic_statusLabel = NULL;
    ui_statusLabel = NULL;
    uic_Pin3 = NULL;
    ui_Pin3 = NULL;
    uic_Pin2 = NULL;
    ui_Pin2 = NULL;
    uic_Pin1 = NULL;
    ui_Pin1 = NULL;
    uic_btnE = NULL;
    ui_btnE = NULL;
    ui_Label6 = NULL;
    uic_btnC = NULL;
    ui_btnC = NULL;
    ui_Label7 = NULL;
    uic_btn4 = NULL;
    ui_btn4 = NULL;
    ui_Label8 = NULL;
    uic_btn7 = NULL;
    ui_btn7 = NULL;
    ui_Label9 = NULL;
    uic_btn0 = NULL;
    ui_btn0 = NULL;
    ui_Label10 = NULL;
    uic_btn8 = NULL;
    ui_btn8 = NULL;
    ui_Label11 = NULL;
    uic_btn5 = NULL;
    ui_btn5 = NULL;
    ui_Label12 = NULL;
    uic_btn6 = NULL;
    ui_btn6 = NULL;
    ui_Label13 = NULL;
    uic_btn9 = NULL;
    ui_btn9 = NULL;
    ui_Label14 = NULL;

}
