// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_btn1(lv_event_t * e);
extern lv_obj_t * ui_btn1;
extern lv_obj_t * ui_Label3;
extern void ui_event_btn2(lv_event_t * e);
extern lv_obj_t * ui_btn2;
extern lv_obj_t * ui_Label4;
extern void ui_event_btn3(lv_event_t * e);
extern lv_obj_t * ui_btn3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Pin0;
extern lv_obj_t * ui_statusLabel;
extern lv_obj_t * ui_Pin3;
extern lv_obj_t * ui_Pin2;
extern lv_obj_t * ui_Pin1;
extern void ui_event_btnE(lv_event_t * e);
extern lv_obj_t * ui_btnE;
extern lv_obj_t * ui_Label6;
extern void ui_event_btnC(lv_event_t * e);
extern lv_obj_t * ui_btnC;
extern lv_obj_t * ui_Label7;
extern void ui_event_btn4(lv_event_t * e);
extern lv_obj_t * ui_btn4;
extern lv_obj_t * ui_Label8;
extern void ui_event_btn7(lv_event_t * e);
extern lv_obj_t * ui_btn7;
extern lv_obj_t * ui_Label9;
extern void ui_event_btn0(lv_event_t * e);
extern lv_obj_t * ui_btn0;
extern lv_obj_t * ui_Label10;
extern void ui_event_btn8(lv_event_t * e);
extern lv_obj_t * ui_btn8;
extern lv_obj_t * ui_Label11;
extern void ui_event_btn5(lv_event_t * e);
extern lv_obj_t * ui_btn5;
extern lv_obj_t * ui_Label12;
extern void ui_event_btn6(lv_event_t * e);
extern lv_obj_t * ui_btn6;
extern lv_obj_t * ui_Label13;
extern void ui_event_btn9(lv_event_t * e);
extern lv_obj_t * ui_btn9;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES
extern lv_obj_t * uic_btn1;
extern lv_obj_t * uic_btn2;
extern lv_obj_t * uic_btn3;
extern lv_obj_t * uic_Pin0;
extern lv_obj_t * uic_statusLabel;
extern lv_obj_t * uic_Pin3;
extern lv_obj_t * uic_Pin2;
extern lv_obj_t * uic_Pin1;
extern lv_obj_t * uic_btnE;
extern lv_obj_t * uic_btnC;
extern lv_obj_t * uic_btn4;
extern lv_obj_t * uic_btn7;
extern lv_obj_t * uic_btn0;
extern lv_obj_t * uic_btn8;
extern lv_obj_t * uic_btn5;
extern lv_obj_t * uic_btn6;
extern lv_obj_t * uic_btn9;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

