// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_InitializePage.h"
#include "screens/ui_PasswordPage.h"
#include "screens/ui_DashboardPage.h"
#include "screens/ui_SensorPage.h"
#include "screens/ui_RecordPage.h"
#include "screens/ui_SettingPage.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * ani1_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_spinner_png);    // assets/spinner.png
LV_IMG_DECLARE(ui_img_sensor_png);    // assets/sensor.png
LV_IMG_DECLARE(ui_img_record_png);    // assets/record.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_logout_png);    // assets/logout.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_intensity_png);    // assets/intensity.png
LV_IMG_DECLARE(ui_img_save_png);    // assets/save.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
