// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"
#include "user/user.h"
#include "usart/usart.h"
#include "sensor/sensor.h"
#include "page/page.h"
#include "page/sensor_page/sensor_page.h"
#include "page/setting_page/setting_page.h"
#include <stdio.h>
#include <stdbool.h>

void num_btn_pressed(lv_event_t * e);
void enter_btn_pressed(lv_event_t * e);
void clear_btn_pressed(lv_event_t * e);
void sensor_reading_on_screen_loaded(lv_event_t * e);
void sensor_reading_on_screen_unloaded(lv_event_t * e);
void record_on_screen_loaded(lv_event_t * e);
void prev_on_click(lv_event_t * e);
void next_on_click(lv_event_t * e);
void setting_on_screen_loaded(lv_event_t * e);
void temp_hum_on_save(lv_event_t * e);
void temp_thres_inc(lv_event_t * e);
void temp_thres_dec(lv_event_t * e);
void hum_thres_inc(lv_event_t * e);
void hum_thres_dec(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
