// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui_events.h"

// from main code
extern char buffer[50];

// ui event
void num_btn_pressed(lv_event_t * e){
    lv_obj_t * btn = lv_event_get_target(e);
    lv_obj_t * label = lv_obj_get_child(btn, 0);

    if(label == NULL){
        USART1_send_string("ERROR: No label\r\n");
        return;
    }

    const char * num_str = lv_label_get_text(label);

    num_btn_onc(num_str);
}

void enter_btn_pressed(lv_event_t * e){
	enter_btn_onc();
}

void clear_btn_pressed(lv_event_t * e){
	clr_btn_onc();
}

void sensor_reading_on_screen_loaded(lv_event_t * e) {
	sensor_page_start();
}

void sensor_reading_on_screen_unloaded(lv_event_t * e) {
	sensor_page_stop();
}

void record_on_screen_loaded(lv_event_t * e) {
	record_page_start();
}

void prev_on_click(lv_event_t * e){
	record_page_prev_onc();
}

void next_on_click(lv_event_t * e){
	record_page_next_onc();
}

void setting_on_screen_loaded(lv_event_t * e) {
	Threshold threshold = get_threshold();
	sprintf(buffer, "%d", threshold.temp_threshold);
	lv_label_set_text(ui_TempThresValSt, buffer);
	sprintf(buffer, "%d", threshold.hum_threshold);
	lv_label_set_text(ui_HumThresValSt, buffer);
}

void temp_hum_on_save(lv_event_t * e) {
	lv_label_set_text(ui_SaveLabelSt, "SAVING...");
	lv_obj_add_state(ui_SettingPage, LV_STATE_DISABLED);
	save_threshold();
	lv_label_set_text(ui_SaveLabelSt, "SAVE");
	lv_obj_clear_state(ui_SettingPage, LV_STATE_DISABLED);
	dashboard();

}

void temp_thres_inc(lv_event_t * e) {
	int inc_val = temp_inc(true);
	if (inc_val != -1) {
		sprintf(buffer, "%d", inc_val);
		lv_label_set_text(ui_TempThresValSt, buffer);
	}
}

void temp_thres_dec(lv_event_t * e) {
	int inc_val = temp_inc(false);
	if (inc_val != -1) {
		sprintf(buffer, "%d", inc_val);
		lv_label_set_text(ui_TempThresValSt, buffer);
	}
}

void hum_thres_inc(lv_event_t * e) {
	int inc_val = hum_inc(true);
	if (inc_val != -1) {
		sprintf(buffer, "%d", inc_val);
		lv_label_set_text(ui_HumThresValSt, buffer);
	}

}

void hum_thres_dec(lv_event_t * e) {
	int inc_val = hum_inc(false);
	if (inc_val != -1) {
		sprintf(buffer, "%d", inc_val);
		lv_label_set_text(ui_HumThresValSt, buffer);
	}
}
