/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2026-08-13

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f429i_discovery.h"
#include "tm_stm32f4_ili9341.h"
#include "tm_stm32f4_fonts.h"
#include "tm_stm32f4_stmpe811.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */
#include "defines.h"
#include "lvgl.h"
#include "ui.h"
#include "string.h"

#include <stdbool.h>
#include <stdio.h>

#include "user/user.h"
#include "usart/usart.h"
#include "gpio/gpio.h"
#include "timer/timer.h"

/* LCD resolution in Landscape */
#define LCD_WIDTH   320
#define LCD_HEIGHT  240

/* LVGL draw buffer */
static lv_color_t buf1[LCD_WIDTH * 20];
char buffer[50];
lv_obj_t *title;

// user
User user;
Usart1 usart1 = {
	.port = GPIOA,
	.tx_pin = GPIO_Pin_9,
	.rx_pin = GPIO_Pin_10,
    .tx_source = GPIO_PinSource9,
	.rx_source = GPIO_PinSource10,
	.baudrate = 115200
};
Gpio gpio_obled = {
	.pin = GPIO_Pin_13 | GPIO_Pin_14
};

Gpio gpio_btn = {
	.pin = GPIO_Pin_5
};

Timer timer3 =
{
    .timer = TIM3,
    .timer_clock = RCC_APB1Periph_TIM3,
	// 90mhz / 900 = 100000 tick per sec
	// so 1 tick is 1/100000 = 1x10^-5
	// then we set period to 100 becase 1x10^-5 x100 = 1ms
    .prescaler = 899, // got + 1 here
    .period = 99, // got +1 here
    .irq_channel = TIM3_IRQn,
    .preemption_priority = 0,
    .sub_priority = 0
};








TM_STMPE811_TouchData touchData;
static void my_flush_cb(
    lv_display_t *display,
    const lv_area_t *area,
    uint8_t *px_map)
{
    TM_ILI9341_DrawBuffer(
    		area->x1,
			area->y1,
			area->x2,
			area->y2,
			(uint16_t *)px_map
	);

    lv_display_flush_ready(display);
}
void my_touchpad_read(lv_indev_t * indev, lv_indev_data_t * data)
{
    char msg[50];

    if (TM_STMPE811_ReadTouch(&touchData) == TM_STMPE811_State_Pressed){
        data->state = LV_INDEV_STATE_PRESSED;

        data->point.x = touchData.y;
        data->point.y = 240 - touchData.x;

        sprintf(
            msg,
            "Touch X=%d Y=%d\r\n",
            data->point.x,
            data->point.y
        );

        USART1_send_string(msg);
    }else{
        data->state = LV_INDEV_STATE_RELEASED;
    }
}

static void switch_to_main(lv_timer_t *timer)
{
	_ui_screen_change(
		&ui_Screen2,
		LV_SCR_LOAD_ANIM_FADE_ON,
		500,
		0,
		&ui_Screen2_screen_init
	);

    lv_timer_del(timer);
}


int main(void)
{
	// usart initialize
	user_init(&user);
	USART1_init(&usart1);
	USART1_send_string("Initializing...\r\n");
	USART1_send_string("Usart Initialize Success!\r\n");

	// user initialize
	user_init(&user);
	USART1_send_string("User Initialize Success!\r\n");

	// lcd screen init
	TM_ILI9341_Init();
	USART1_send_string("LCD Initialize Success!\r\n");

	// lvgl init
	lv_init();
	USART1_send_string("LVGL Initialize Success!\r\n");

	// gpio init
	GPIO_obLED_init(&gpio_obled);
	GPIO_btn_init(&gpio_btn);
	USART1_send_string("GPIO Initialize Success!\r\n");

	// timer and interrupt init
	timer_init(&timer3);
	timer_NVIC_init(&timer3);
	USART1_send_string("Timer Initialize Success!\r\n");

	// touch screen
	TM_STMPE811_Init();
	USART1_send_string("TMSTMPE811 Success!\r\n");


    USART1_send_string("Initialization Finish!\r\n");



    TM_ILI9341_Rotate(TM_ILI9341_Orientation_Landscape_1);

    lv_display_t *display = lv_display_create(320, 240);

    lv_display_set_buffers(
        display,
        buf1,
        NULL,
        sizeof(buf1),
        LV_DISPLAY_RENDER_MODE_PARTIAL
    );

    lv_display_set_flush_cb(
        display,
        my_flush_cb
    );

    /* Create LVGL touch input device */
    lv_indev_t *indev = lv_indev_create();

    lv_indev_set_type(
    	indev,
        LV_INDEV_TYPE_POINTER
    );

    lv_indev_set_read_cb(
        indev,
        my_touchpad_read
    );

    ui_init();

    TIM_Cmd(timer3.timer, ENABLE);

    lv_timer_create(
        switch_to_main,
        5000,
        NULL
    );



    while (1)
    {
        lv_timer_handler();

    }
}

/*
 * Callback used by stm324xg_eval_i2c_ee.c.
 * Refer to stm324xg_eval_i2c_ee.h for more info.
 */
uint32_t sEE_TIMEOUT_UserCallback(void)
{
  /* TODO, implement your code here */
  while (1)
  {
  }
}
