/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2026-08-13

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f429i_discovery.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */
#include "defines.h"
#include "lvgl.h"
#include "ui.h"
#include "string.h"

#include <stdbool.h>
#include <stdio.h>

#include "user/user.h"
#include "usart/usart.h"
#include "gpio/gpio.h"
#include "timer/timer.h"
#include "page/page.h"
#include "page/setting_page/setting_page.h"
#include "page/initialize_page/initialize_page.h"
char buffer[50];
// user
User user;
Usart1 usart1 = {
	.port = GPIOA,
	.tx_pin = GPIO_Pin_9,
	.rx_pin = GPIO_Pin_10,
    .tx_source = GPIO_PinSource9,
	.rx_source = GPIO_PinSource10,
	.baudrate = 115200
};
Gpio gpio_obled = {
	.pin = GPIO_Pin_13 | GPIO_Pin_14
};

Gpio gpio_btn = {
	.pin = GPIO_Pin_5
};

// timer for lvgl
Timer timer3 = {
    .timer = TIM3,
    .timer_clock = RCC_APB1Periph_TIM3,
	// 90mhz / 900 = 100000 tick per sec
	// so 1 tick is 1/100000 = 1x10^-5
	// then we set period to 100 becase 1x10^-5 x100 = 1ms
    .prescaler = 899, // got + 1 here
    .period = 99, // got +1 here
    .irq_channel = TIM3_IRQn,
    .preemption_priority = 0,
    .sub_priority = 0,
	.enable_interrupt = true
};

// timer by dht22, it use tim2 go and see the source file
Timer timer2 = {
	.timer = TIM2,
	.timer_clock = RCC_APB1Periph_TIM2,
	.prescaler = (uint16_t) (90000000 / 1000000) - 1,
	.period = 65535 - 1,
	.enable_interrupt = false
};

// timer4 for dc motor
Timer timer4 = {
	.timer = TIM4,
	.timer_clock = RCC_APB1Periph_TIM4,
	// timer tick freq = 84000000 / (0 + 1) = 84000000
	// period = 84000000 / 50000 - 1 = 1680
	.prescaler = 0,
	.period = 1680,
};


// threshold
Threshold threshold = {
	.temp_threshold = 20,
	.hum_threshold = 30,
	.indecrement = 1
};

static void switch_to_main(lv_timer_t *timer)
{
	password();

    lv_timer_del(timer);
}


int main(void)
{
	// usart initialize
	USART1_init(&usart1);
	USART1_send_string("Initializing...\r\n");
	USART1_send_string("Usart Initialize Success!\r\n");

	// user initialize
	user_init(&user);
	USART1_send_string("User Initialize Success!\r\n");

	// lcd screen init
	TM_ILI9341_Init();
	USART1_send_string("LCD Initialize Success!\r\n");

	// lvgl init
	lv_init();
	USART1_send_string("LVGL Initialize Success!\r\n");

	// gpio init
	GPIO_obLED_init(&gpio_obled);
	GPIO_btn_init(&gpio_btn);
	USART1_send_string("GPIO Initialize Success!\r\n");

	// timer and interrupt init
	timer_init(&timer3);
	timer_NVIC_init(&timer3);
	timer_init(&timer2);
	TIM_Cmd(timer3.timer, ENABLE);
	TIM_Cmd(timer2.timer, ENABLE);
	USART1_send_string("Timer Initialize Success!\r\n");

	// touch screen
	TM_STMPE811_Init();
	USART1_send_string("TMSTMPE811 Initialize Success!\r\n");

	// dht22 ldr init
	DHT22_Init();
	LDR_Init();
	USART1_send_string("DHT22 Initialize Success!\r\n");

	// threshold value init
	temp_hum_threshold_init(threshold);

	// nand
	FMC_NAND_Init();

	FMC_NAND_Test();

    USART1_send_string("Initialization Finish!\r\n");
    screen_init();

    ui_init();

    lv_timer_create(
        switch_to_main,
        5000,
        NULL
    );
    while (1) {
		lv_timer_handler();

    }
}

/*
 * Callback used by stm324xg_eval_i2c_ee.c.
 * Refer to stm324xg_eval_i2c_ee.h for more info.
 */
uint32_t sEE_TIMEOUT_UserCallback(void)
{
  /* TODO, implement your code here */
  while (1)
  {
  }
}
