// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_BottomNavSettingD;
lv_obj_t * uic_BottomNavRecordD;
lv_obj_t * uic_BottomNavSensorD;
lv_obj_t * uic_BottomNavDashboardD;
lv_obj_t * uic_BottomNavD;
lv_obj_t * uic_LogoutLabelD;
lv_obj_t * uic_LogoutImageD;
lv_obj_t * uic_LogoutPanelD;
lv_obj_t * uic_SettingLabelD;
lv_obj_t * uic_SettingImageD;
lv_obj_t * uic_SettingPanelD;
lv_obj_t * uic_RecordLabelD;
lv_obj_t * uic_RecordPanelD;
lv_obj_t * uic_SensorLabelD;
lv_obj_t * uic_SensorPanelD;
lv_obj_t * ui_DashboardPage = NULL;
lv_obj_t * ui_DashboardLabelD = NULL;
lv_obj_t * ui_OnlineLabelD = NULL;
lv_obj_t * ui_OnlineStatusD = NULL;
lv_obj_t * ui_SensorPanelD = NULL;
lv_obj_t * ui_SensorLabelD = NULL;
lv_obj_t * ui_RecordPanelD = NULL;
lv_obj_t * ui_RecordLabelD = NULL;
lv_obj_t * ui_SettingPanelD = NULL;
lv_obj_t * ui_SettingImageD = NULL;
lv_obj_t * ui_SettingLabelD = NULL;
lv_obj_t * ui_LogoutPanelD = NULL;
lv_obj_t * ui_LogoutImageD = NULL;
lv_obj_t * ui_LogoutLabelD = NULL;
lv_obj_t * ui_BottomNavD = NULL;
lv_obj_t * ui_BottomNavDashboardD = NULL;
lv_obj_t * ui_BottomNavSensorD = NULL;
lv_obj_t * ui_BottomNavRecordD = NULL;
lv_obj_t * ui_BottomNavSettingD = NULL;
// event funtions

// build funtions

void ui_DashboardPage_screen_init(void)
{
    ui_DashboardPage = lv_obj_create(NULL);
    lv_obj_add_flag(ui_DashboardPage, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_DashboardPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_DashboardPage, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_DashboardPage, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_DashboardPage, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DashboardPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DashboardLabelD = lv_label_create(ui_DashboardPage);
    lv_obj_set_width(ui_DashboardLabelD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DashboardLabelD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DashboardLabelD, -88);
    lv_obj_set_y(ui_DashboardLabelD, -101);
    lv_obj_set_align(ui_DashboardLabelD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DashboardLabelD, "DASHBOARD");
    lv_obj_set_style_text_color(ui_DashboardLabelD, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DashboardLabelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnlineLabelD = lv_label_create(ui_DashboardPage);
    lv_obj_set_width(ui_OnlineLabelD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnlineLabelD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnlineLabelD, 105);
    lv_obj_set_y(ui_OnlineLabelD, -101);
    lv_obj_set_align(ui_OnlineLabelD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnlineLabelD, "Online");
    lv_obj_set_style_text_color(ui_OnlineLabelD, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OnlineLabelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OnlineLabelD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnlineStatusD = lv_obj_create(ui_DashboardPage);
    lv_obj_set_width(ui_OnlineStatusD, 10);
    lv_obj_set_height(ui_OnlineStatusD, 10);
    lv_obj_set_x(ui_OnlineStatusD, 135);
    lv_obj_set_y(ui_OnlineStatusD, -100);
    lv_obj_set_align(ui_OnlineStatusD, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_OnlineStatusD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_OnlineStatusD, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OnlineStatusD, lv_color_hex(0x08F334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OnlineStatusD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OnlineStatusD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorPanelD = lv_obj_create(ui_DashboardPage);
    lv_obj_set_width(ui_SensorPanelD, 100);
    lv_obj_set_height(ui_SensorPanelD, 100);
    lv_obj_set_x(ui_SensorPanelD, -90);
    lv_obj_set_y(ui_SensorPanelD, -35);
    lv_obj_set_align(ui_SensorPanelD, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SensorPanelD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SensorPanelD, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorPanelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SensorPanelD, &ui_img_sensor_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SensorPanelD, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SensorPanelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SensorPanelD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SensorPanelD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SensorPanelD, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SensorPanelD, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SensorPanelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SensorPanelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SensorPanelD, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorLabelD = lv_label_create(ui_SensorPanelD);
    lv_obj_set_width(ui_SensorLabelD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorLabelD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SensorLabelD, 1);
    lv_obj_set_y(ui_SensorLabelD, 34);
    lv_obj_set_align(ui_SensorLabelD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SensorLabelD, "Sensor");
    lv_obj_set_style_text_color(ui_SensorLabelD, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SensorLabelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SensorLabelD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SensorLabelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SensorLabelD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordPanelD = lv_obj_create(ui_DashboardPage);
    lv_obj_set_width(ui_RecordPanelD, 170);
    lv_obj_set_height(ui_RecordPanelD, 100);
    lv_obj_set_x(ui_RecordPanelD, 60);
    lv_obj_set_y(ui_RecordPanelD, -35);
    lv_obj_set_align(ui_RecordPanelD, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RecordPanelD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RecordPanelD, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordPanelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_RecordPanelD, &ui_img_record_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RecordPanelD, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RecordPanelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RecordPanelD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RecordPanelD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RecordPanelD, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RecordPanelD, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RecordPanelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_RecordPanelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_RecordPanelD, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordLabelD = lv_label_create(ui_RecordPanelD);
    lv_obj_set_width(ui_RecordLabelD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordLabelD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordLabelD, 1);
    lv_obj_set_y(ui_RecordLabelD, 40);
    lv_obj_set_align(ui_RecordLabelD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordLabelD, "Record");
    lv_obj_set_style_text_color(ui_RecordLabelD, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordLabelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_RecordLabelD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_RecordLabelD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecordLabelD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingPanelD = lv_obj_create(ui_DashboardPage);
    lv_obj_set_width(ui_SettingPanelD, 100);
    lv_obj_set_height(ui_SettingPanelD, 35);
    lv_obj_set_x(ui_SettingPanelD, -90);
    lv_obj_set_y(ui_SettingPanelD, 45);
    lv_obj_set_align(ui_SettingPanelD, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingPanelD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingPanelD, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPanelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingPanelD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingPanelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SettingPanelD, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SettingPanelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SettingPanelD, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SettingPanelD, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingImageD = lv_image_create(ui_SettingPanelD);
    lv_image_set_src(ui_SettingImageD, &ui_img_setting_png);
    lv_obj_set_width(ui_SettingImageD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingImageD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingImageD, -27);
    lv_obj_set_y(ui_SettingImageD, 1);
    lv_obj_set_align(ui_SettingImageD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingImageD, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SettingImageD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingLabelD = lv_label_create(ui_SettingPanelD);
    lv_obj_set_width(ui_SettingLabelD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingLabelD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingLabelD, 14);
    lv_obj_set_y(ui_SettingLabelD, -1);
    lv_obj_set_align(ui_SettingLabelD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingLabelD, "Setting");
    lv_obj_set_style_text_color(ui_SettingLabelD, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingLabelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SettingLabelD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SettingLabelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingLabelD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoutPanelD = lv_obj_create(ui_DashboardPage);
    lv_obj_set_width(ui_LogoutPanelD, 170);
    lv_obj_set_height(ui_LogoutPanelD, 35);
    lv_obj_set_x(ui_LogoutPanelD, 60);
    lv_obj_set_y(ui_LogoutPanelD, 45);
    lv_obj_set_align(ui_LogoutPanelD, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LogoutPanelD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogoutPanelD, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogoutPanelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LogoutPanelD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LogoutPanelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LogoutPanelD, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LogoutPanelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_LogoutPanelD, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_LogoutPanelD, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoutImageD = lv_image_create(ui_LogoutPanelD);
    lv_image_set_src(ui_LogoutImageD, &ui_img_logout_png);
    lv_obj_set_width(ui_LogoutImageD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoutImageD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoutImageD, -30);
    lv_obj_set_y(ui_LogoutImageD, -1);
    lv_obj_set_align(ui_LogoutImageD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoutImageD, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LogoutImageD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoutLabelD = lv_label_create(ui_LogoutPanelD);
    lv_obj_set_width(ui_LogoutLabelD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoutLabelD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoutLabelD, 15);
    lv_obj_set_y(ui_LogoutLabelD, -1);
    lv_obj_set_align(ui_LogoutLabelD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LogoutLabelD, "Log Out");
    lv_obj_set_style_text_color(ui_LogoutLabelD, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LogoutLabelD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LogoutLabelD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LogoutLabelD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LogoutLabelD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavD = lv_obj_create(ui_DashboardPage);
    lv_obj_set_width(ui_BottomNavD, 334);
    lv_obj_set_height(ui_BottomNavD, 50);
    lv_obj_set_x(ui_BottomNavD, 2);
    lv_obj_set_y(ui_BottomNavD, 115);
    lv_obj_set_align(ui_BottomNavD, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BottomNavD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomNavD, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomNavD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomNavD, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomNavD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomNavD, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomNavD, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavDashboardD = lv_label_create(ui_DashboardPage);
    lv_obj_set_width(ui_BottomNavDashboardD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavDashboardD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavDashboardD, -110);
    lv_obj_set_y(ui_BottomNavDashboardD, 105);
    lv_obj_set_align(ui_BottomNavDashboardD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavDashboardD, "HOME");
    lv_obj_set_style_text_color(ui_BottomNavDashboardD, lv_color_hex(0x08F334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavDashboardD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavDashboardD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSensorD = lv_label_create(ui_DashboardPage);
    lv_obj_set_width(ui_BottomNavSensorD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSensorD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSensorD, -40);
    lv_obj_set_y(ui_BottomNavSensorD, 105);
    lv_obj_set_align(ui_BottomNavSensorD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSensorD, "SENSOR");
    lv_obj_set_style_text_color(ui_BottomNavSensorD, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSensorD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSensorD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavRecordD = lv_label_create(ui_DashboardPage);
    lv_obj_set_width(ui_BottomNavRecordD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavRecordD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavRecordD, 30);
    lv_obj_set_y(ui_BottomNavRecordD, 105);
    lv_obj_set_align(ui_BottomNavRecordD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavRecordD, "RECORD");
    lv_obj_set_style_text_color(ui_BottomNavRecordD, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavRecordD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavRecordD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSettingD = lv_label_create(ui_DashboardPage);
    lv_obj_set_width(ui_BottomNavSettingD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSettingD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSettingD, 100);
    lv_obj_set_y(ui_BottomNavSettingD, 105);
    lv_obj_set_align(ui_BottomNavSettingD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSettingD, "SETTING");
    lv_obj_set_style_text_color(ui_BottomNavSettingD, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSettingD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSettingD, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_SensorPanelD = ui_SensorPanelD;
    uic_SensorLabelD = ui_SensorLabelD;
    uic_RecordPanelD = ui_RecordPanelD;
    uic_RecordLabelD = ui_RecordLabelD;
    uic_SettingPanelD = ui_SettingPanelD;
    uic_SettingImageD = ui_SettingImageD;
    uic_SettingLabelD = ui_SettingLabelD;
    uic_LogoutPanelD = ui_LogoutPanelD;
    uic_LogoutImageD = ui_LogoutImageD;
    uic_LogoutLabelD = ui_LogoutLabelD;
    uic_BottomNavD = ui_BottomNavD;
    uic_BottomNavDashboardD = ui_BottomNavDashboardD;
    uic_BottomNavSensorD = ui_BottomNavSensorD;
    uic_BottomNavRecordD = ui_BottomNavRecordD;
    uic_BottomNavSettingD = ui_BottomNavSettingD;

}

void ui_DashboardPage_screen_destroy(void)
{
    if(ui_DashboardPage) lv_obj_del(ui_DashboardPage);

    // NULL screen variables
    ui_DashboardPage = NULL;
    ui_DashboardLabelD = NULL;
    ui_OnlineLabelD = NULL;
    ui_OnlineStatusD = NULL;
    uic_SensorPanelD = NULL;
    ui_SensorPanelD = NULL;
    uic_SensorLabelD = NULL;
    ui_SensorLabelD = NULL;
    uic_RecordPanelD = NULL;
    ui_RecordPanelD = NULL;
    uic_RecordLabelD = NULL;
    ui_RecordLabelD = NULL;
    uic_SettingPanelD = NULL;
    ui_SettingPanelD = NULL;
    uic_SettingImageD = NULL;
    ui_SettingImageD = NULL;
    uic_SettingLabelD = NULL;
    ui_SettingLabelD = NULL;
    uic_LogoutPanelD = NULL;
    ui_LogoutPanelD = NULL;
    uic_LogoutImageD = NULL;
    ui_LogoutImageD = NULL;
    uic_LogoutLabelD = NULL;
    ui_LogoutLabelD = NULL;
    uic_BottomNavD = NULL;
    ui_BottomNavD = NULL;
    uic_BottomNavDashboardD = NULL;
    ui_BottomNavDashboardD = NULL;
    uic_BottomNavSensorD = NULL;
    ui_BottomNavSensorD = NULL;
    uic_BottomNavRecordD = NULL;
    ui_BottomNavRecordD = NULL;
    uic_BottomNavSettingD = NULL;
    ui_BottomNavSettingD = NULL;

}
