// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_DASHBOARDPAGE_H
#define UI_DASHBOARDPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DashboardPage
extern void ui_DashboardPage_screen_init(void);
extern void ui_DashboardPage_screen_destroy(void);
extern lv_obj_t * ui_DashboardPage;
extern lv_obj_t * ui_DashboardLabelD;
extern lv_obj_t * ui_OnlineLabelD;
extern lv_obj_t * ui_OnlineStatusD;
extern void ui_event_SensorPanelD(lv_event_t * e);
extern lv_obj_t * ui_SensorPanelD;
extern lv_obj_t * ui_SensorLabelD;
extern void ui_event_RecordPanelD(lv_event_t * e);
extern lv_obj_t * ui_RecordPanelD;
extern lv_obj_t * ui_RecordLabelD;
extern void ui_event_SettingPanelD(lv_event_t * e);
extern lv_obj_t * ui_SettingPanelD;
extern lv_obj_t * ui_SettingImageD;
extern lv_obj_t * ui_SettingLabelD;
extern void ui_event_LogoutPanelD(lv_event_t * e);
extern lv_obj_t * ui_LogoutPanelD;
extern lv_obj_t * ui_LogoutImageD;
extern lv_obj_t * ui_LogoutLabelD;
extern lv_obj_t * ui_BottomNavD;
extern lv_obj_t * ui_BottomNavDashboardD;
extern void ui_event_BottomNavSensorD(lv_event_t * e);
extern lv_obj_t * ui_BottomNavSensorD;
extern void ui_event_BottomNavRecordD(lv_event_t * e);
extern lv_obj_t * ui_BottomNavRecordD;
extern void ui_event_BottomNavSettingD(lv_event_t * e);
extern lv_obj_t * ui_BottomNavSettingD;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SensorPanelD;
extern lv_obj_t * uic_SensorLabelD;
extern lv_obj_t * uic_RecordPanelD;
extern lv_obj_t * uic_RecordLabelD;
extern lv_obj_t * uic_SettingPanelD;
extern lv_obj_t * uic_SettingImageD;
extern lv_obj_t * uic_SettingLabelD;
extern lv_obj_t * uic_LogoutPanelD;
extern lv_obj_t * uic_LogoutImageD;
extern lv_obj_t * uic_LogoutLabelD;
extern lv_obj_t * uic_BottomNavD;
extern lv_obj_t * uic_BottomNavDashboardD;
extern lv_obj_t * uic_BottomNavSensorD;
extern lv_obj_t * uic_BottomNavRecordD;
extern lv_obj_t * uic_BottomNavSettingD;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

