// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_InitializeImage;
lv_obj_t * uic_InitializeMsg1;
lv_obj_t * ui_InitializePage = NULL;
lv_obj_t * ui_InitializeMsg1 = NULL;
lv_obj_t * ui_InitializeImage = NULL;
lv_obj_t * ui_InitializeMsg2 = NULL;
// event funtions
void ui_event_InitializePage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ani1_Animation(ui_InitializeImage, 0);
    }
}

// build funtions

void ui_InitializePage_screen_init(void)
{
    ui_InitializePage = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_InitializePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InitializePage, lv_color_hex(0x0F172A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InitializePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InitializeMsg1 = lv_label_create(ui_InitializePage);
    lv_obj_set_width(ui_InitializeMsg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InitializeMsg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InitializeMsg1, lv_pct(1));
    lv_obj_set_y(ui_InitializeMsg1, lv_pct(-20));
    lv_obj_set_align(ui_InitializeMsg1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InitializeMsg1, "Welcome to MySmartBox");
    lv_obj_set_style_text_color(ui_InitializeMsg1, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InitializeMsg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_InitializeMsg1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_InitializeMsg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InitializeImage = lv_image_create(ui_InitializePage);
    lv_image_set_src(ui_InitializeImage, &ui_img_spinner_png);
    lv_obj_set_width(ui_InitializeImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InitializeImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InitializeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InitializeImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_InitializeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_InitializeImage, 100);

    ui_InitializeMsg2 = lv_label_create(ui_InitializePage);
    lv_obj_set_width(ui_InitializeMsg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InitializeMsg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InitializeMsg2, -1);
    lv_obj_set_y(ui_InitializeMsg2, 37);
    lv_obj_set_align(ui_InitializeMsg2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InitializeMsg2, "Initializing...");
    lv_obj_set_style_text_color(ui_InitializeMsg2, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InitializeMsg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_InitializeMsg2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_InitializeMsg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InitializeMsg2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_InitializePage, ui_event_InitializePage, LV_EVENT_ALL, NULL);
    uic_InitializeMsg1 = ui_InitializeMsg1;
    uic_InitializeImage = ui_InitializeImage;

}

void ui_InitializePage_screen_destroy(void)
{
    if(ui_InitializePage) lv_obj_del(ui_InitializePage);

    // NULL screen variables
    ui_InitializePage = NULL;
    uic_InitializeMsg1 = NULL;
    ui_InitializeMsg1 = NULL;
    uic_InitializeImage = NULL;
    ui_InitializeImage = NULL;
    ui_InitializeMsg2 = NULL;

}
