// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_INITIALIZEPAGE_H
#define UI_INITIALIZEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InitializePage
extern void ui_InitializePage_screen_init(void);
extern void ui_InitializePage_screen_destroy(void);
extern void ui_event_InitializePage(lv_event_t * e);
extern lv_obj_t * ui_InitializePage;
extern lv_obj_t * ui_InitializeMsg1;
extern lv_obj_t * ui_InitializeImage;
extern lv_obj_t * ui_InitializeMsg2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_InitializeMsg1;
extern lv_obj_t * uic_InitializeImage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

