// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_PASSWORDPAGE_H
#define UI_PASSWORDPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PasswordPage
extern void ui_PasswordPage_screen_init(void);
extern void ui_PasswordPage_screen_destroy(void);
extern lv_obj_t * ui_PasswordPage;
extern lv_obj_t * ui_StatusLabel;
extern lv_obj_t * ui_Pin0;
extern lv_obj_t * ui_Pin1;
extern lv_obj_t * ui_Pin2;
extern lv_obj_t * ui_Pin3;
extern void ui_event_btn1(lv_event_t * e);
extern lv_obj_t * ui_btn1;
extern lv_obj_t * ui_btnLabel1;
extern void ui_event_btn2(lv_event_t * e);
extern lv_obj_t * ui_btn2;
extern lv_obj_t * ui_btnLabel2;
extern void ui_event_btn3(lv_event_t * e);
extern lv_obj_t * ui_btn3;
extern lv_obj_t * ui_btnLabel3;
extern void ui_event_btn4(lv_event_t * e);
extern lv_obj_t * ui_btn4;
extern lv_obj_t * ui_btnLabel4;
extern void ui_event_btn5(lv_event_t * e);
extern lv_obj_t * ui_btn5;
extern lv_obj_t * ui_btnLabel5;
extern void ui_event_btn6(lv_event_t * e);
extern lv_obj_t * ui_btn6;
extern lv_obj_t * ui_btnLabel6;
extern void ui_event_btn7(lv_event_t * e);
extern lv_obj_t * ui_btn7;
extern lv_obj_t * ui_btnLabel7;
extern void ui_event_btn8(lv_event_t * e);
extern lv_obj_t * ui_btn8;
extern lv_obj_t * ui_btnLabel8;
extern void ui_event_btn9(lv_event_t * e);
extern lv_obj_t * ui_btn9;
extern lv_obj_t * ui_btnLabel9;
extern void ui_event_btn0(lv_event_t * e);
extern lv_obj_t * ui_btn0;
extern lv_obj_t * ui_btnLabel0;
extern void ui_event_btnLabelE(lv_event_t * e);
extern lv_obj_t * ui_btnLabelE;
extern lv_obj_t * ui_Label6;
extern void ui_event_btnC(lv_event_t * e);
extern lv_obj_t * ui_btnC;
extern lv_obj_t * ui_btnLabelC;
// CUSTOM VARIABLES
extern lv_obj_t * uic_StatusLabel;
extern lv_obj_t * uic_Pin0;
extern lv_obj_t * uic_Pin1;
extern lv_obj_t * uic_Pin2;
extern lv_obj_t * uic_Pin3;
extern lv_obj_t * uic_btn1;
extern lv_obj_t * uic_btnLabel1;
extern lv_obj_t * uic_btn2;
extern lv_obj_t * uic_btnLabel2;
extern lv_obj_t * uic_btn3;
extern lv_obj_t * uic_btnLabel3;
extern lv_obj_t * uic_btn4;
extern lv_obj_t * uic_btnLabel4;
extern lv_obj_t * uic_btn5;
extern lv_obj_t * uic_btnLabel5;
extern lv_obj_t * uic_btn6;
extern lv_obj_t * uic_btnLabel6;
extern lv_obj_t * uic_btn7;
extern lv_obj_t * uic_btnLabel7;
extern lv_obj_t * uic_btn8;
extern lv_obj_t * uic_btnLabel8;
extern lv_obj_t * uic_btn9;
extern lv_obj_t * uic_btnLabel9;
extern lv_obj_t * uic_btn0;
extern lv_obj_t * uic_btnLabel0;
extern lv_obj_t * uic_btnLabelE;
extern lv_obj_t * uic_btnC;
extern lv_obj_t * uic_btnLabelC;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

