// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_NextLabelR;
lv_obj_t * uic_PageLabelR;
lv_obj_t * uic_PrevLabelR;
lv_obj_t * uic_BottomNavSettingR;
lv_obj_t * uic_BottomNavRecordR;
lv_obj_t * uic_BottomNavSensorR;
lv_obj_t * uic_RecordData5R;
lv_obj_t * uic_RecordDate5R;
lv_obj_t * uic_RecordPanel5R;
lv_obj_t * uic_RecordData4R;
lv_obj_t * uic_RecordDate4R;
lv_obj_t * uic_RecordPanel4R;
lv_obj_t * uic_RecordData3R;
lv_obj_t * uic_RecordDate3R;
lv_obj_t * uic_RecordPanel3R;
lv_obj_t * uic_RecordData2R;
lv_obj_t * uic_RecordDate2R;
lv_obj_t * uic_RecordPanel2R;
lv_obj_t * uic_RecordData1R;
lv_obj_t * uic_RecordDate1R;
lv_obj_t * uic_RecordPanel1R;
lv_obj_t * uic_RecordContainerR;
lv_obj_t * uic_RecordLabelR;
lv_obj_t * uic_RecordPage;
lv_obj_t * ui_RecordPage = NULL;
lv_obj_t * ui_RecordLabelR = NULL;
lv_obj_t * ui_RecordContainerR = NULL;
lv_obj_t * ui_RecordPanel1R = NULL;
lv_obj_t * ui_RecordDate1R = NULL;
lv_obj_t * ui_RecordData1R = NULL;
lv_obj_t * ui_RecordPanel2R = NULL;
lv_obj_t * ui_RecordDate2R = NULL;
lv_obj_t * ui_RecordData2R = NULL;
lv_obj_t * ui_RecordPanel3R = NULL;
lv_obj_t * ui_RecordDate3R = NULL;
lv_obj_t * ui_RecordData3R = NULL;
lv_obj_t * ui_RecordPanel4R = NULL;
lv_obj_t * ui_RecordDate4R = NULL;
lv_obj_t * ui_RecordData4R = NULL;
lv_obj_t * ui_RecordPanel5R = NULL;
lv_obj_t * ui_RecordDate5R = NULL;
lv_obj_t * ui_RecordData5R = NULL;
lv_obj_t * ui_BottomNavR = NULL;
lv_obj_t * ui_BottomNavDashboardR = NULL;
lv_obj_t * ui_BottomNavSensorR = NULL;
lv_obj_t * ui_BottomNavRecordR = NULL;
lv_obj_t * ui_BottomNavSettingR = NULL;
lv_obj_t * ui_PrevLabelR = NULL;
lv_obj_t * ui_PageLabelR = NULL;
lv_obj_t * ui_NextLabelR = NULL;
// event funtions
void ui_event_RecordPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        record_on_screen_loaded(e);
    }
}

void ui_event_BottomNavDashboardR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DashboardPage, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_DashboardPage_screen_init);
    }
}

void ui_event_BottomNavSensorR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SensorPage, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_SensorPage_screen_init);
    }
}

void ui_event_BottomNavSettingR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingPage, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_SettingPage_screen_init);
    }
}

void ui_event_PrevLabelR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        prev_on_click(e);
    }
}

void ui_event_PageLabelR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        next_on_click(e);
    }
}

// build funtions

void ui_RecordPage_screen_init(void)
{
    ui_RecordPage = lv_obj_create(NULL);
    lv_obj_add_flag(ui_RecordPage, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_RecordPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_RecordPage, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_RecordPage, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_RecordPage, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordLabelR = lv_label_create(ui_RecordPage);
    lv_obj_set_width(ui_RecordLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordLabelR, -106);
    lv_obj_set_y(ui_RecordLabelR, -101);
    lv_obj_set_align(ui_RecordLabelR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordLabelR, "RECORD");
    lv_obj_set_style_text_color(ui_RecordLabelR, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordContainerR = lv_obj_create(ui_RecordPage);
    lv_obj_remove_style_all(ui_RecordContainerR);
    lv_obj_set_width(ui_RecordContainerR, 275);
    lv_obj_set_height(ui_RecordContainerR, 156);
    lv_obj_set_x(ui_RecordContainerR, 0);
    lv_obj_set_y(ui_RecordContainerR, -3);
    lv_obj_set_align(ui_RecordContainerR, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RecordContainerR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RecordContainerR, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RecordContainerR, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordContainerR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RecordContainerR, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RecordContainerR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RecordContainerR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RecordContainerR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RecordContainerR, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RecordContainerR, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RecordContainerR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_RecordContainerR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_RecordContainerR, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordPanel1R = lv_obj_create(ui_RecordContainerR);
    lv_obj_set_width(ui_RecordPanel1R, 257);
    lv_obj_set_height(ui_RecordPanel1R, 25);
    lv_obj_set_x(ui_RecordPanel1R, -2);
    lv_obj_set_y(ui_RecordPanel1R, -59);
    lv_obj_set_align(ui_RecordPanel1R, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RecordPanel1R, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RecordPanel1R, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordPanel1R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RecordPanel1R, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RecordPanel1R, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RecordPanel1R, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RecordPanel1R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_RecordPanel1R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_RecordPanel1R, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordDate1R = lv_label_create(ui_RecordPanel1R);
    lv_obj_set_width(ui_RecordDate1R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordDate1R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordDate1R, -71);
    lv_obj_set_y(ui_RecordDate1R, -8);
    lv_obj_set_align(ui_RecordDate1R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordDate1R, "DD MMM YYYY - HH:MM");
    lv_obj_set_style_text_color(ui_RecordDate1R, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordDate1R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecordDate1R, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordData1R = lv_label_create(ui_RecordPanel1R);
    lv_obj_set_width(ui_RecordData1R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordData1R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordData1R, -1);
    lv_obj_set_y(ui_RecordData1R, 3);
    lv_obj_set_align(ui_RecordData1R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordData1R, "   --.- °C   |   --.-% Hum   |   --.-% LDR");
    lv_obj_set_style_text_font(ui_RecordData1R, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordPanel2R = lv_obj_create(ui_RecordContainerR);
    lv_obj_set_width(ui_RecordPanel2R, 257);
    lv_obj_set_height(ui_RecordPanel2R, 25);
    lv_obj_set_x(ui_RecordPanel2R, -3);
    lv_obj_set_y(ui_RecordPanel2R, -30);
    lv_obj_set_align(ui_RecordPanel2R, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RecordPanel2R, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RecordPanel2R, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordPanel2R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RecordPanel2R, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RecordPanel2R, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RecordPanel2R, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RecordPanel2R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_RecordPanel2R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_RecordPanel2R, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordDate2R = lv_label_create(ui_RecordPanel2R);
    lv_obj_set_width(ui_RecordDate2R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordDate2R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordDate2R, -71);
    lv_obj_set_y(ui_RecordDate2R, -8);
    lv_obj_set_align(ui_RecordDate2R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordDate2R, "DD MMM YYYY - HH:MM");
    lv_obj_set_style_text_color(ui_RecordDate2R, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordDate2R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecordDate2R, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordData2R = lv_label_create(ui_RecordPanel2R);
    lv_obj_set_width(ui_RecordData2R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordData2R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordData2R, -1);
    lv_obj_set_y(ui_RecordData2R, 3);
    lv_obj_set_align(ui_RecordData2R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordData2R, "   --.- °C   |   --.-% Hum   |   --.-% LDR");
    lv_obj_set_style_text_font(ui_RecordData2R, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordPanel3R = lv_obj_create(ui_RecordContainerR);
    lv_obj_set_width(ui_RecordPanel3R, 257);
    lv_obj_set_height(ui_RecordPanel3R, 25);
    lv_obj_set_x(ui_RecordPanel3R, -3);
    lv_obj_set_y(ui_RecordPanel3R, -2);
    lv_obj_set_align(ui_RecordPanel3R, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RecordPanel3R, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RecordPanel3R, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordPanel3R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RecordPanel3R, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RecordPanel3R, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RecordPanel3R, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RecordPanel3R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_RecordPanel3R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_RecordPanel3R, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordDate3R = lv_label_create(ui_RecordPanel3R);
    lv_obj_set_width(ui_RecordDate3R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordDate3R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordDate3R, -71);
    lv_obj_set_y(ui_RecordDate3R, -8);
    lv_obj_set_align(ui_RecordDate3R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordDate3R, "DD MMM YYYY - HH:MM");
    lv_obj_set_style_text_color(ui_RecordDate3R, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordDate3R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecordDate3R, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordData3R = lv_label_create(ui_RecordPanel3R);
    lv_obj_set_width(ui_RecordData3R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordData3R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordData3R, -1);
    lv_obj_set_y(ui_RecordData3R, 3);
    lv_obj_set_align(ui_RecordData3R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordData3R, "   --.- °C   |   --.-% Hum   |   --.-% LDR");
    lv_obj_set_style_text_font(ui_RecordData3R, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordPanel4R = lv_obj_create(ui_RecordContainerR);
    lv_obj_set_width(ui_RecordPanel4R, 257);
    lv_obj_set_height(ui_RecordPanel4R, 25);
    lv_obj_set_x(ui_RecordPanel4R, -2);
    lv_obj_set_y(ui_RecordPanel4R, 26);
    lv_obj_set_align(ui_RecordPanel4R, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RecordPanel4R, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RecordPanel4R, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordPanel4R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RecordPanel4R, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RecordPanel4R, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RecordPanel4R, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RecordPanel4R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_RecordPanel4R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_RecordPanel4R, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordDate4R = lv_label_create(ui_RecordPanel4R);
    lv_obj_set_width(ui_RecordDate4R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordDate4R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordDate4R, -71);
    lv_obj_set_y(ui_RecordDate4R, -8);
    lv_obj_set_align(ui_RecordDate4R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordDate4R, "DD MMM YYYY - HH:MM");
    lv_obj_set_style_text_color(ui_RecordDate4R, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordDate4R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecordDate4R, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordData4R = lv_label_create(ui_RecordPanel4R);
    lv_obj_set_width(ui_RecordData4R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordData4R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordData4R, -1);
    lv_obj_set_y(ui_RecordData4R, 3);
    lv_obj_set_align(ui_RecordData4R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordData4R, "   --.- °C   |   --.-% Hum   |   --.-% LDR");
    lv_obj_set_style_text_font(ui_RecordData4R, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordPanel5R = lv_obj_create(ui_RecordContainerR);
    lv_obj_set_width(ui_RecordPanel5R, 257);
    lv_obj_set_height(ui_RecordPanel5R, 25);
    lv_obj_set_x(ui_RecordPanel5R, -2);
    lv_obj_set_y(ui_RecordPanel5R, 54);
    lv_obj_set_align(ui_RecordPanel5R, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RecordPanel5R, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RecordPanel5R, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordPanel5R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RecordPanel5R, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RecordPanel5R, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RecordPanel5R, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RecordPanel5R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_RecordPanel5R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_RecordPanel5R, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordDate5R = lv_label_create(ui_RecordPanel5R);
    lv_obj_set_width(ui_RecordDate5R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordDate5R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordDate5R, -71);
    lv_obj_set_y(ui_RecordDate5R, -8);
    lv_obj_set_align(ui_RecordDate5R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordDate5R, "DD MMM YYYY - HH:MM");
    lv_obj_set_style_text_color(ui_RecordDate5R, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordDate5R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecordDate5R, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordData5R = lv_label_create(ui_RecordPanel5R);
    lv_obj_set_width(ui_RecordData5R, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordData5R, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordData5R, -1);
    lv_obj_set_y(ui_RecordData5R, 3);
    lv_obj_set_align(ui_RecordData5R, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordData5R, "   --.- °C   |   --.-% Hum   |   --.-% LDR");
    lv_obj_set_style_text_font(ui_RecordData5R, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavR = lv_obj_create(ui_RecordPage);
    lv_obj_set_width(ui_BottomNavR, 334);
    lv_obj_set_height(ui_BottomNavR, 50);
    lv_obj_set_x(ui_BottomNavR, 2);
    lv_obj_set_y(ui_BottomNavR, 113);
    lv_obj_set_align(ui_BottomNavR, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BottomNavR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomNavR, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomNavR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomNavR, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomNavR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomNavR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomNavR, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavDashboardR = lv_label_create(ui_RecordPage);
    lv_obj_set_width(ui_BottomNavDashboardR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavDashboardR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavDashboardR, -110);
    lv_obj_set_y(ui_BottomNavDashboardR, 105);
    lv_obj_set_align(ui_BottomNavDashboardR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavDashboardR, "HOME");
    lv_obj_add_flag(ui_BottomNavDashboardR, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BottomNavDashboardR, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavDashboardR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavDashboardR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSensorR = lv_label_create(ui_RecordPage);
    lv_obj_set_width(ui_BottomNavSensorR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSensorR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSensorR, -40);
    lv_obj_set_y(ui_BottomNavSensorR, 105);
    lv_obj_set_align(ui_BottomNavSensorR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSensorR, "SENSOR");
    lv_obj_add_flag(ui_BottomNavSensorR, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BottomNavSensorR, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSensorR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSensorR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavRecordR = lv_label_create(ui_RecordPage);
    lv_obj_set_width(ui_BottomNavRecordR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavRecordR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavRecordR, 30);
    lv_obj_set_y(ui_BottomNavRecordR, 105);
    lv_obj_set_align(ui_BottomNavRecordR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavRecordR, "RECORD");
    lv_obj_set_style_text_color(ui_BottomNavRecordR, lv_color_hex(0x08F334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavRecordR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavRecordR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSettingR = lv_label_create(ui_RecordPage);
    lv_obj_set_width(ui_BottomNavSettingR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSettingR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSettingR, 100);
    lv_obj_set_y(ui_BottomNavSettingR, 105);
    lv_obj_set_align(ui_BottomNavSettingR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSettingR, "SETTING");
    lv_obj_add_flag(ui_BottomNavSettingR, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BottomNavSettingR, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSettingR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSettingR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrevLabelR = lv_label_create(ui_RecordPage);
    lv_obj_set_width(ui_PrevLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrevLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrevLabelR, 15);
    lv_obj_set_y(ui_PrevLabelR, -90);
    lv_obj_set_align(ui_PrevLabelR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrevLabelR, "<Prev");
    lv_obj_set_style_text_font(ui_PrevLabelR, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PageLabelR = lv_label_create(ui_RecordPage);
    lv_obj_set_width(ui_PageLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PageLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PageLabelR, 115);
    lv_obj_set_y(ui_PageLabelR, -90);
    lv_obj_set_align(ui_PageLabelR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PageLabelR, "Next>");
    lv_obj_set_style_text_font(ui_PageLabelR, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextLabelR = lv_label_create(ui_RecordPage);
    lv_obj_set_width(ui_NextLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NextLabelR, 65);
    lv_obj_set_y(ui_NextLabelR, -90);
    lv_obj_set_align(ui_NextLabelR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NextLabelR, "Page 1");
    lv_obj_set_style_text_color(ui_NextLabelR, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NextLabelR, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NextLabelR, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BottomNavDashboardR, ui_event_BottomNavDashboardR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BottomNavSensorR, ui_event_BottomNavSensorR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BottomNavSettingR, ui_event_BottomNavSettingR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrevLabelR, ui_event_PrevLabelR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PageLabelR, ui_event_PageLabelR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RecordPage, ui_event_RecordPage, LV_EVENT_ALL, NULL);
    uic_RecordPage = ui_RecordPage;
    uic_RecordLabelR = ui_RecordLabelR;
    uic_RecordContainerR = ui_RecordContainerR;
    uic_RecordPanel1R = ui_RecordPanel1R;
    uic_RecordDate1R = ui_RecordDate1R;
    uic_RecordData1R = ui_RecordData1R;
    uic_RecordPanel2R = ui_RecordPanel2R;
    uic_RecordDate2R = ui_RecordDate2R;
    uic_RecordData2R = ui_RecordData2R;
    uic_RecordPanel3R = ui_RecordPanel3R;
    uic_RecordDate3R = ui_RecordDate3R;
    uic_RecordData3R = ui_RecordData3R;
    uic_RecordPanel4R = ui_RecordPanel4R;
    uic_RecordDate4R = ui_RecordDate4R;
    uic_RecordData4R = ui_RecordData4R;
    uic_RecordPanel5R = ui_RecordPanel5R;
    uic_RecordDate5R = ui_RecordDate5R;
    uic_RecordData5R = ui_RecordData5R;
    uic_BottomNavSensorR = ui_BottomNavSensorR;
    uic_BottomNavRecordR = ui_BottomNavRecordR;
    uic_BottomNavSettingR = ui_BottomNavSettingR;
    uic_PrevLabelR = ui_PrevLabelR;
    uic_PageLabelR = ui_PageLabelR;
    uic_NextLabelR = ui_NextLabelR;

}

void ui_RecordPage_screen_destroy(void)
{
    if(ui_RecordPage) lv_obj_del(ui_RecordPage);

    // NULL screen variables
    uic_RecordPage = NULL;
    ui_RecordPage = NULL;
    uic_RecordLabelR = NULL;
    ui_RecordLabelR = NULL;
    uic_RecordContainerR = NULL;
    ui_RecordContainerR = NULL;
    uic_RecordPanel1R = NULL;
    ui_RecordPanel1R = NULL;
    uic_RecordDate1R = NULL;
    ui_RecordDate1R = NULL;
    uic_RecordData1R = NULL;
    ui_RecordData1R = NULL;
    uic_RecordPanel2R = NULL;
    ui_RecordPanel2R = NULL;
    uic_RecordDate2R = NULL;
    ui_RecordDate2R = NULL;
    uic_RecordData2R = NULL;
    ui_RecordData2R = NULL;
    uic_RecordPanel3R = NULL;
    ui_RecordPanel3R = NULL;
    uic_RecordDate3R = NULL;
    ui_RecordDate3R = NULL;
    uic_RecordData3R = NULL;
    ui_RecordData3R = NULL;
    uic_RecordPanel4R = NULL;
    ui_RecordPanel4R = NULL;
    uic_RecordDate4R = NULL;
    ui_RecordDate4R = NULL;
    uic_RecordData4R = NULL;
    ui_RecordData4R = NULL;
    uic_RecordPanel5R = NULL;
    ui_RecordPanel5R = NULL;
    uic_RecordDate5R = NULL;
    ui_RecordDate5R = NULL;
    uic_RecordData5R = NULL;
    ui_RecordData5R = NULL;
    ui_BottomNavR = NULL;
    ui_BottomNavDashboardR = NULL;
    uic_BottomNavSensorR = NULL;
    ui_BottomNavSensorR = NULL;
    uic_BottomNavRecordR = NULL;
    ui_BottomNavRecordR = NULL;
    uic_BottomNavSettingR = NULL;
    ui_BottomNavSettingR = NULL;
    uic_PrevLabelR = NULL;
    ui_PrevLabelR = NULL;
    uic_PageLabelR = NULL;
    ui_PageLabelR = NULL;
    uic_NextLabelR = NULL;
    ui_NextLabelR = NULL;

}
