// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_RECORDPAGE_H
#define UI_RECORDPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RecordPage
extern void ui_RecordPage_screen_init(void);
extern void ui_RecordPage_screen_destroy(void);
extern lv_obj_t * ui_RecordPage;
extern lv_obj_t * ui_RecordLabelR;
extern lv_obj_t * ui_RecordContainerR;
extern lv_obj_t * ui_RecordPanel1R;
extern lv_obj_t * ui_RecordDate1R;
extern lv_obj_t * ui_RecordData1R;
extern lv_obj_t * ui_RecordPanel2R;
extern lv_obj_t * ui_RecordDate2R;
extern lv_obj_t * ui_RecordData2R;
extern lv_obj_t * ui_RecordPanel3R;
extern lv_obj_t * ui_RecordDate3R;
extern lv_obj_t * ui_RecordData3R;
extern lv_obj_t * ui_RecordPanel4R;
extern lv_obj_t * ui_RecordDate4R;
extern lv_obj_t * ui_RecordData4R;
extern lv_obj_t * ui_RecordPanel5R;
extern lv_obj_t * ui_RecordDate5R;
extern lv_obj_t * ui_RecordData5R;
extern lv_obj_t * ui_BottomNavR;
extern lv_obj_t * ui_BottomNavDashboardR;
extern lv_obj_t * ui_BottomNavSensorR;
extern lv_obj_t * ui_BottomNavRecordR;
extern lv_obj_t * ui_BottomNavSettingR;
extern lv_obj_t * ui_PrevLabelR;
extern lv_obj_t * ui_PageLabelR;
extern lv_obj_t * ui_NextLabelR;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RecordPage;
extern lv_obj_t * uic_RecordLabelR;
extern lv_obj_t * uic_RecordContainerR;
extern lv_obj_t * uic_RecordPanel1R;
extern lv_obj_t * uic_RecordDate1R;
extern lv_obj_t * uic_RecordData1R;
extern lv_obj_t * uic_RecordPanel2R;
extern lv_obj_t * uic_RecordDate2R;
extern lv_obj_t * uic_RecordData2R;
extern lv_obj_t * uic_RecordPanel3R;
extern lv_obj_t * uic_RecordDate3R;
extern lv_obj_t * uic_RecordData3R;
extern lv_obj_t * uic_RecordPanel4R;
extern lv_obj_t * uic_RecordDate4R;
extern lv_obj_t * uic_RecordData4R;
extern lv_obj_t * uic_RecordPanel5R;
extern lv_obj_t * uic_RecordDate5R;
extern lv_obj_t * uic_RecordData5R;
extern lv_obj_t * uic_BottomNavSensorR;
extern lv_obj_t * uic_BottomNavRecordR;
extern lv_obj_t * uic_BottomNavSettingR;
extern lv_obj_t * uic_PrevLabelR;
extern lv_obj_t * uic_PageLabelR;
extern lv_obj_t * uic_NextLabelR;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

