// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_BottomNavSettingS;
lv_obj_t * uic_BottomNavRecordS;
lv_obj_t * uic_BottomNavSensorS;
lv_obj_t * uic_BottomNavDashboardS;
lv_obj_t * uic_BottomNavS;
lv_obj_t * uic_SaveS;
lv_obj_t * uic_SaveLabelS;
lv_obj_t * uic_SaveImageS;
lv_obj_t * uic_SavePanelS;
lv_obj_t * uic_IntensityUnitS;
lv_obj_t * uic_IntensityS;
lv_obj_t * uic_IntensityImageS;
lv_obj_t * uic_IntensityPanelS;
lv_obj_t * uic_HumidityUnitLabelS;
lv_obj_t * uic_HumidityS;
lv_obj_t * uic_HumidityImageS;
lv_obj_t * uic_HumidityLabelS;
lv_obj_t * uic_HumidityPanelS;
lv_obj_t * uic_TemperatureUnitLabelS;
lv_obj_t * uic_TemperatureS;
lv_obj_t * uic_TemperatureImageS;
lv_obj_t * uic_TemperatureLabelS;
lv_obj_t * uic_TemperaturePanelS;
lv_obj_t * uic_SensorLabelS;
lv_obj_t * uic_SensorPage;
lv_obj_t * ui_SensorPage = NULL;
lv_obj_t * ui_SensorLabelS = NULL;
lv_obj_t * ui_TemperaturePanelS = NULL;
lv_obj_t * ui_TemperatureLabelS = NULL;
lv_obj_t * ui_TemperatureImageS = NULL;
lv_obj_t * ui_TemperatureS = NULL;
lv_obj_t * ui_TemperatureUnitLabelS = NULL;
lv_obj_t * ui_HumidityPanelS = NULL;
lv_obj_t * ui_HumidityLabelS = NULL;
lv_obj_t * ui_HumidityImageS = NULL;
lv_obj_t * ui_HumidityS = NULL;
lv_obj_t * ui_HumidityUnitLabelS = NULL;
lv_obj_t * ui_IntensityPanelS = NULL;
lv_obj_t * ui_IntensityLabelS = NULL;
lv_obj_t * ui_IntensityImageS = NULL;
lv_obj_t * ui_IntensityS = NULL;
lv_obj_t * ui_IntensityUnitS = NULL;
lv_obj_t * ui_SavePanelS = NULL;
lv_obj_t * ui_SaveImageS = NULL;
lv_obj_t * ui_SaveLabelS = NULL;
lv_obj_t * ui_SaveS = NULL;
lv_obj_t * ui_SaveTotalLabelS = NULL;
lv_obj_t * ui_BottomNavS = NULL;
lv_obj_t * ui_BottomNavDashboardS = NULL;
lv_obj_t * ui_BottomNavSensorS = NULL;
lv_obj_t * ui_BottomNavRecordS = NULL;
lv_obj_t * ui_BottomNavSettingS = NULL;
// event funtions

// build funtions

void ui_SensorPage_screen_init(void)
{
    ui_SensorPage = lv_obj_create(NULL);
    lv_obj_add_flag(ui_SensorPage, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_SensorPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SensorPage, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_SensorPage, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_SensorPage, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorLabelS = lv_label_create(ui_SensorPage);
    lv_obj_set_width(ui_SensorLabelS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorLabelS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SensorLabelS, -106);
    lv_obj_set_y(ui_SensorLabelS, -101);
    lv_obj_set_align(ui_SensorLabelS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SensorLabelS, "SENSOR");
    lv_obj_set_style_text_color(ui_SensorLabelS, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SensorLabelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperaturePanelS = lv_obj_create(ui_SensorPage);
    lv_obj_set_width(ui_TemperaturePanelS, 80);
    lv_obj_set_height(ui_TemperaturePanelS, 100);
    lv_obj_set_x(ui_TemperaturePanelS, -95);
    lv_obj_set_y(ui_TemperaturePanelS, -35);
    lv_obj_set_align(ui_TemperaturePanelS, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TemperaturePanelS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TemperaturePanelS, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperaturePanelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemperaturePanelS, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemperaturePanelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TemperaturePanelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TemperaturePanelS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TemperaturePanelS, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TemperaturePanelS, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TemperaturePanelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_TemperaturePanelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_TemperaturePanelS, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureLabelS = lv_label_create(ui_TemperaturePanelS);
    lv_obj_set_width(ui_TemperatureLabelS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabelS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureLabelS, 0);
    lv_obj_set_y(ui_TemperatureLabelS, -40);
    lv_obj_set_align(ui_TemperatureLabelS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabelS, "Temperature");
    lv_obj_set_style_text_color(ui_TemperatureLabelS, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureLabelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureLabelS, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureImageS = lv_image_create(ui_TemperaturePanelS);
    lv_image_set_src(ui_TemperatureImageS, &ui_img_temperature_png);
    lv_obj_set_width(ui_TemperatureImageS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureImageS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureImageS, -2);
    lv_obj_set_y(ui_TemperatureImageS, -10);
    lv_obj_set_align(ui_TemperatureImageS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TemperatureImageS, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TemperatureImageS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_TemperatureImageS, 155);

    ui_TemperatureS = lv_label_create(ui_TemperaturePanelS);
    lv_obj_set_width(ui_TemperatureS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureS, -10);
    lv_obj_set_y(ui_TemperatureS, 30);
    lv_obj_set_align(ui_TemperatureS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureS, "--.-");
    lv_obj_set_style_text_color(ui_TemperatureS, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureUnitLabelS = lv_label_create(ui_TemperaturePanelS);
    lv_obj_set_width(ui_TemperatureUnitLabelS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureUnitLabelS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureUnitLabelS, 15);
    lv_obj_set_y(ui_TemperatureUnitLabelS, 30);
    lv_obj_set_align(ui_TemperatureUnitLabelS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureUnitLabelS, "°C");
    lv_obj_set_style_text_color(ui_TemperatureUnitLabelS, lv_color_hex(0xF97316), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureUnitLabelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TemperatureUnitLabelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TemperatureUnitLabelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureUnitLabelS, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityPanelS = lv_obj_create(ui_SensorPage);
    lv_obj_set_width(ui_HumidityPanelS, 80);
    lv_obj_set_height(ui_HumidityPanelS, 100);
    lv_obj_set_x(ui_HumidityPanelS, 0);
    lv_obj_set_y(ui_HumidityPanelS, -35);
    lv_obj_set_align(ui_HumidityPanelS, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HumidityPanelS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumidityPanelS, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumidityPanelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HumidityPanelS, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HumidityPanelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HumidityPanelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HumidityPanelS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HumidityPanelS, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HumidityPanelS, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HumidityPanelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_HumidityPanelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_HumidityPanelS, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabelS = lv_label_create(ui_HumidityPanelS);
    lv_obj_set_width(ui_HumidityLabelS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabelS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityLabelS, 0);
    lv_obj_set_y(ui_HumidityLabelS, -40);
    lv_obj_set_align(ui_HumidityLabelS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabelS, "Humidity");
    lv_obj_set_style_text_color(ui_HumidityLabelS, lv_color_hex(0x06B6D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityLabelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityLabelS, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityImageS = lv_image_create(ui_HumidityPanelS);
    lv_image_set_src(ui_HumidityImageS, &ui_img_humidity_png);
    lv_obj_set_width(ui_HumidityImageS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityImageS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityImageS, 2);
    lv_obj_set_y(ui_HumidityImageS, -7);
    lv_obj_set_align(ui_HumidityImageS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumidityImageS, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_HumidityImageS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_HumidityImageS, 140);

    ui_HumidityS = lv_label_create(ui_HumidityPanelS);
    lv_obj_set_width(ui_HumidityS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityS, -10);
    lv_obj_set_y(ui_HumidityS, 30);
    lv_obj_set_align(ui_HumidityS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityS, "--.-");
    lv_obj_set_style_text_color(ui_HumidityS, lv_color_hex(0x06B6D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityUnitLabelS = lv_label_create(ui_HumidityPanelS);
    lv_obj_set_width(ui_HumidityUnitLabelS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityUnitLabelS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityUnitLabelS, 15);
    lv_obj_set_y(ui_HumidityUnitLabelS, 30);
    lv_obj_set_align(ui_HumidityUnitLabelS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityUnitLabelS, "%");
    lv_obj_set_style_text_color(ui_HumidityUnitLabelS, lv_color_hex(0x06B6D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityUnitLabelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HumidityUnitLabelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HumidityUnitLabelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityUnitLabelS, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntensityPanelS = lv_obj_create(ui_SensorPage);
    lv_obj_set_width(ui_IntensityPanelS, 80);
    lv_obj_set_height(ui_IntensityPanelS, 100);
    lv_obj_set_x(ui_IntensityPanelS, 95);
    lv_obj_set_y(ui_IntensityPanelS, -35);
    lv_obj_set_align(ui_IntensityPanelS, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_IntensityPanelS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IntensityPanelS, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IntensityPanelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IntensityPanelS, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IntensityPanelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IntensityPanelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_IntensityPanelS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_IntensityPanelS, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_IntensityPanelS, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_IntensityPanelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_IntensityPanelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_IntensityPanelS, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntensityLabelS = lv_label_create(ui_IntensityPanelS);
    lv_obj_set_width(ui_IntensityLabelS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IntensityLabelS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IntensityLabelS, 0);
    lv_obj_set_y(ui_IntensityLabelS, -40);
    lv_obj_set_align(ui_IntensityLabelS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IntensityLabelS, "Intensity");
    lv_obj_set_style_text_color(ui_IntensityLabelS, lv_color_hex(0xEAB308), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntensityLabelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IntensityLabelS, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntensityImageS = lv_image_create(ui_IntensityPanelS);
    lv_image_set_src(ui_IntensityImageS, &ui_img_intensity_png);
    lv_obj_set_width(ui_IntensityImageS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IntensityImageS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IntensityImageS, 2);
    lv_obj_set_y(ui_IntensityImageS, -7);
    lv_obj_set_align(ui_IntensityImageS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IntensityImageS, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_IntensityImageS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_IntensityImageS, 255);

    ui_IntensityS = lv_label_create(ui_IntensityPanelS);
    lv_obj_set_width(ui_IntensityS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IntensityS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IntensityS, -10);
    lv_obj_set_y(ui_IntensityS, 30);
    lv_obj_set_align(ui_IntensityS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IntensityS, "--.-");
    lv_obj_set_style_text_color(ui_IntensityS, lv_color_hex(0xEAB308), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntensityS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IntensityUnitS = lv_label_create(ui_IntensityPanelS);
    lv_obj_set_width(ui_IntensityUnitS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IntensityUnitS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IntensityUnitS, 15);
    lv_obj_set_y(ui_IntensityUnitS, 30);
    lv_obj_set_align(ui_IntensityUnitS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IntensityUnitS, "%");
    lv_obj_set_style_text_color(ui_IntensityUnitS, lv_color_hex(0xEAB308), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IntensityUnitS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IntensityUnitS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IntensityUnitS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IntensityUnitS, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SavePanelS = lv_obj_create(ui_SensorPage);
    lv_obj_set_width(ui_SavePanelS, 275);
    lv_obj_set_height(ui_SavePanelS, 35);
    lv_obj_set_x(ui_SavePanelS, 0);
    lv_obj_set_y(ui_SavePanelS, 45);
    lv_obj_set_align(ui_SavePanelS, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SavePanelS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SavePanelS, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavePanelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SavePanelS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SavePanelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SavePanelS, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SavePanelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SavePanelS, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SavePanelS, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveImageS = lv_image_create(ui_SavePanelS);
    lv_image_set_src(ui_SaveImageS, &ui_img_save_png);
    lv_obj_set_width(ui_SaveImageS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveImageS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveImageS, -56);
    lv_obj_set_y(ui_SaveImageS, -1);
    lv_obj_set_align(ui_SaveImageS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveImageS, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SaveImageS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SaveLabelS = lv_label_create(ui_SavePanelS);
    lv_obj_set_width(ui_SaveLabelS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabelS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabelS, -21);
    lv_obj_set_y(ui_SaveLabelS, -1);
    lv_obj_set_align(ui_SaveLabelS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabelS, "SAVE");
    lv_obj_set_style_text_color(ui_SaveLabelS, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveLabelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveLabelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveLabelS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveS = lv_label_create(ui_SavePanelS);
    lv_obj_set_width(ui_SaveS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveS, 11);
    lv_obj_set_y(ui_SaveS, -1);
    lv_obj_set_align(ui_SaveS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveS, "0");
    lv_obj_set_style_text_color(ui_SaveS, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveTotalLabelS = lv_label_create(ui_SavePanelS);
    lv_obj_set_width(ui_SaveTotalLabelS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveTotalLabelS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveTotalLabelS, 22);
    lv_obj_set_y(ui_SaveTotalLabelS, -1);
    lv_obj_set_align(ui_SaveTotalLabelS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveTotalLabelS, "/5");
    lv_obj_set_style_text_color(ui_SaveTotalLabelS, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveTotalLabelS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveTotalLabelS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveTotalLabelS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveTotalLabelS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavS = lv_obj_create(ui_SensorPage);
    lv_obj_set_width(ui_BottomNavS, 334);
    lv_obj_set_height(ui_BottomNavS, 50);
    lv_obj_set_x(ui_BottomNavS, 2);
    lv_obj_set_y(ui_BottomNavS, 115);
    lv_obj_set_align(ui_BottomNavS, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BottomNavS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomNavS, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomNavS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomNavS, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomNavS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomNavS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomNavS, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavDashboardS = lv_label_create(ui_SensorPage);
    lv_obj_set_width(ui_BottomNavDashboardS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavDashboardS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavDashboardS, -110);
    lv_obj_set_y(ui_BottomNavDashboardS, 105);
    lv_obj_set_align(ui_BottomNavDashboardS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavDashboardS, "HOME");
    lv_obj_set_style_text_color(ui_BottomNavDashboardS, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavDashboardS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavDashboardS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSensorS = lv_label_create(ui_SensorPage);
    lv_obj_set_width(ui_BottomNavSensorS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSensorS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSensorS, -40);
    lv_obj_set_y(ui_BottomNavSensorS, 105);
    lv_obj_set_align(ui_BottomNavSensorS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSensorS, "SENSOR");
    lv_obj_set_style_text_color(ui_BottomNavSensorS, lv_color_hex(0x08F334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSensorS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSensorS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavRecordS = lv_label_create(ui_SensorPage);
    lv_obj_set_width(ui_BottomNavRecordS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavRecordS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavRecordS, 30);
    lv_obj_set_y(ui_BottomNavRecordS, 105);
    lv_obj_set_align(ui_BottomNavRecordS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavRecordS, "RECORD");
    lv_obj_set_style_text_color(ui_BottomNavRecordS, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavRecordS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavRecordS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSettingS = lv_label_create(ui_SensorPage);
    lv_obj_set_width(ui_BottomNavSettingS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSettingS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSettingS, 100);
    lv_obj_set_y(ui_BottomNavSettingS, 105);
    lv_obj_set_align(ui_BottomNavSettingS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSettingS, "SETTING");
    lv_obj_set_style_text_color(ui_BottomNavSettingS, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSettingS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSettingS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_SensorPage = ui_SensorPage;
    uic_SensorLabelS = ui_SensorLabelS;
    uic_TemperaturePanelS = ui_TemperaturePanelS;
    uic_TemperatureLabelS = ui_TemperatureLabelS;
    uic_TemperatureImageS = ui_TemperatureImageS;
    uic_TemperatureS = ui_TemperatureS;
    uic_TemperatureUnitLabelS = ui_TemperatureUnitLabelS;
    uic_HumidityPanelS = ui_HumidityPanelS;
    uic_HumidityLabelS = ui_HumidityLabelS;
    uic_HumidityImageS = ui_HumidityImageS;
    uic_HumidityS = ui_HumidityS;
    uic_HumidityUnitLabelS = ui_HumidityUnitLabelS;
    uic_IntensityPanelS = ui_IntensityPanelS;
    uic_IntensityImageS = ui_IntensityImageS;
    uic_IntensityS = ui_IntensityS;
    uic_IntensityUnitS = ui_IntensityUnitS;
    uic_SavePanelS = ui_SavePanelS;
    uic_SaveImageS = ui_SaveImageS;
    uic_SaveLabelS = ui_SaveLabelS;
    uic_SaveS = ui_SaveS;
    uic_BottomNavS = ui_BottomNavS;
    uic_BottomNavDashboardS = ui_BottomNavDashboardS;
    uic_BottomNavSensorS = ui_BottomNavSensorS;
    uic_BottomNavRecordS = ui_BottomNavRecordS;
    uic_BottomNavSettingS = ui_BottomNavSettingS;

}

void ui_SensorPage_screen_destroy(void)
{
    if(ui_SensorPage) lv_obj_del(ui_SensorPage);

    // NULL screen variables
    uic_SensorPage = NULL;
    ui_SensorPage = NULL;
    uic_SensorLabelS = NULL;
    ui_SensorLabelS = NULL;
    uic_TemperaturePanelS = NULL;
    ui_TemperaturePanelS = NULL;
    uic_TemperatureLabelS = NULL;
    ui_TemperatureLabelS = NULL;
    uic_TemperatureImageS = NULL;
    ui_TemperatureImageS = NULL;
    uic_TemperatureS = NULL;
    ui_TemperatureS = NULL;
    uic_TemperatureUnitLabelS = NULL;
    ui_TemperatureUnitLabelS = NULL;
    uic_HumidityPanelS = NULL;
    ui_HumidityPanelS = NULL;
    uic_HumidityLabelS = NULL;
    ui_HumidityLabelS = NULL;
    uic_HumidityImageS = NULL;
    ui_HumidityImageS = NULL;
    uic_HumidityS = NULL;
    ui_HumidityS = NULL;
    uic_HumidityUnitLabelS = NULL;
    ui_HumidityUnitLabelS = NULL;
    uic_IntensityPanelS = NULL;
    ui_IntensityPanelS = NULL;
    ui_IntensityLabelS = NULL;
    uic_IntensityImageS = NULL;
    ui_IntensityImageS = NULL;
    uic_IntensityS = NULL;
    ui_IntensityS = NULL;
    uic_IntensityUnitS = NULL;
    ui_IntensityUnitS = NULL;
    uic_SavePanelS = NULL;
    ui_SavePanelS = NULL;
    uic_SaveImageS = NULL;
    ui_SaveImageS = NULL;
    uic_SaveLabelS = NULL;
    ui_SaveLabelS = NULL;
    uic_SaveS = NULL;
    ui_SaveS = NULL;
    ui_SaveTotalLabelS = NULL;
    uic_BottomNavS = NULL;
    ui_BottomNavS = NULL;
    uic_BottomNavDashboardS = NULL;
    ui_BottomNavDashboardS = NULL;
    uic_BottomNavSensorS = NULL;
    ui_BottomNavSensorS = NULL;
    uic_BottomNavRecordS = NULL;
    ui_BottomNavRecordS = NULL;
    uic_BottomNavSettingS = NULL;
    ui_BottomNavSettingS = NULL;

}
