// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_HumThresDecSt;
lv_obj_t * uic_HumThresValSt;
lv_obj_t * uic_HumThresIncSt;
lv_obj_t * uic_HumThresImageSt;
lv_obj_t * uic_HumThresPanelSt;
lv_obj_t * uic_TempThresDecSt;
lv_obj_t * uic_TempThresValSt;
lv_obj_t * uic_TempThresIncSt;
lv_obj_t * uic_TempThresImageSt;
lv_obj_t * uic_TempThresPanelSt;
lv_obj_t * uic_SaveLabelSt;
lv_obj_t * uic_SaveImageSt;
lv_obj_t * uic_SavePanelSt;
lv_obj_t * uic_BottomNavRecordSt;
lv_obj_t * uic_BottomNavSensorSt;
lv_obj_t * uic_BottomNavDashboardSt;
lv_obj_t * uic_BottomNavSt;
lv_obj_t * uic_SettingPage;
lv_obj_t * ui_SettingPage = NULL;
lv_obj_t * ui_SettingLabelSt = NULL;
lv_obj_t * ui_BottomNavSt = NULL;
lv_obj_t * ui_BottomNavDashboardSt = NULL;
lv_obj_t * ui_BottomNavSensorSt = NULL;
lv_obj_t * ui_BottomNavRecordSt = NULL;
lv_obj_t * ui_BottomNavSettingSt = NULL;
lv_obj_t * ui_SavePanelSt = NULL;
lv_obj_t * ui_SaveImageSt = NULL;
lv_obj_t * ui_SaveLabelSt = NULL;
lv_obj_t * ui_TempThresPanelSt = NULL;
lv_obj_t * ui_TempThresImageSt = NULL;
lv_obj_t * ui_TempThresIncSt = NULL;
lv_obj_t * ui_TempThresValSt = NULL;
lv_obj_t * ui_TempThresDecSt = NULL;
lv_obj_t * ui_HumThresPanelSt = NULL;
lv_obj_t * ui_HumThresImageSt = NULL;
lv_obj_t * ui_HumThresIncSt = NULL;
lv_obj_t * ui_HumThresValSt = NULL;
lv_obj_t * ui_HumThresDecSt = NULL;
// event funtions
void ui_event_SettingPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        setting_on_screen_loaded(e);
    }
}

void ui_event_BottomNavDashboardSt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DashboardPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DashboardPage_screen_init);
    }
}

void ui_event_BottomNavSensorSt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SensorPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SensorPage_screen_init);
    }
}

void ui_event_BottomNavRecordSt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RecordPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RecordPage_screen_init);
    }
}

void ui_event_SavePanelSt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        temp_hum_on_save(e);
    }
}

void ui_event_TempThresIncSt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        temp_thres_inc(e);
    }
}

void ui_event_TempThresDecSt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        temp_thres_dec(e);
    }
}

void ui_event_HumThresIncSt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hum_thres_inc(e);
    }
}

void ui_event_HumThresDecSt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hum_thres_dec(e);
    }
}

// build funtions

void ui_SettingPage_screen_init(void)
{
    ui_SettingPage = lv_obj_create(NULL);
    lv_obj_add_flag(ui_SettingPage, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_SettingPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SettingPage, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_SettingPage, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_SettingPage, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingLabelSt = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_SettingLabelSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingLabelSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingLabelSt, -106);
    lv_obj_set_y(ui_SettingLabelSt, -101);
    lv_obj_set_align(ui_SettingLabelSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingLabelSt, "SETTING");
    lv_obj_set_style_text_color(ui_SettingLabelSt, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingLabelSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSt = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavSt, 334);
    lv_obj_set_height(ui_BottomNavSt, 50);
    lv_obj_set_x(ui_BottomNavSt, 2);
    lv_obj_set_y(ui_BottomNavSt, 113);
    lv_obj_set_align(ui_BottomNavSt, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BottomNavSt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomNavSt, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomNavSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomNavSt, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomNavSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomNavSt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomNavSt, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavDashboardSt = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavDashboardSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavDashboardSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavDashboardSt, -110);
    lv_obj_set_y(ui_BottomNavDashboardSt, 105);
    lv_obj_set_align(ui_BottomNavDashboardSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavDashboardSt, "HOME");
    lv_obj_add_flag(ui_BottomNavDashboardSt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BottomNavDashboardSt, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavDashboardSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavDashboardSt, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSensorSt = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavSensorSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSensorSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSensorSt, -40);
    lv_obj_set_y(ui_BottomNavSensorSt, 105);
    lv_obj_set_align(ui_BottomNavSensorSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSensorSt, "SENSOR");
    lv_obj_add_flag(ui_BottomNavSensorSt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BottomNavSensorSt, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSensorSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSensorSt, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavRecordSt = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavRecordSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavRecordSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavRecordSt, 30);
    lv_obj_set_y(ui_BottomNavRecordSt, 105);
    lv_obj_set_align(ui_BottomNavRecordSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavRecordSt, "RECORD");
    lv_obj_add_flag(ui_BottomNavRecordSt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_BottomNavRecordSt, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavRecordSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavRecordSt, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSettingSt = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavSettingSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSettingSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSettingSt, 100);
    lv_obj_set_y(ui_BottomNavSettingSt, 105);
    lv_obj_set_align(ui_BottomNavSettingSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSettingSt, "SETTING");
    lv_obj_set_style_text_color(ui_BottomNavSettingSt, lv_color_hex(0x08F334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSettingSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSettingSt, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SavePanelSt = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_SavePanelSt, 275);
    lv_obj_set_height(ui_SavePanelSt, 35);
    lv_obj_set_x(ui_SavePanelSt, 0);
    lv_obj_set_y(ui_SavePanelSt, 55);
    lv_obj_set_align(ui_SavePanelSt, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SavePanelSt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SavePanelSt, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavePanelSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SavePanelSt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SavePanelSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SavePanelSt, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SavePanelSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SavePanelSt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SavePanelSt, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveImageSt = lv_image_create(ui_SavePanelSt);
    lv_image_set_src(ui_SaveImageSt, &ui_img_save_png);
    lv_obj_set_width(ui_SaveImageSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveImageSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveImageSt, -32);
    lv_obj_set_y(ui_SaveImageSt, 0);
    lv_obj_set_align(ui_SaveImageSt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveImageSt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SaveImageSt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SaveLabelSt = lv_label_create(ui_SavePanelSt);
    lv_obj_set_width(ui_SaveLabelSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabelSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabelSt, 9);
    lv_obj_set_y(ui_SaveLabelSt, 1);
    lv_obj_set_align(ui_SaveLabelSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabelSt, "SAVE");
    lv_obj_set_style_text_color(ui_SaveLabelSt, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabelSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveLabelSt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveLabelSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveLabelSt, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempThresPanelSt = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_TempThresPanelSt, 275);
    lv_obj_set_height(ui_TempThresPanelSt, 55);
    lv_obj_set_x(ui_TempThresPanelSt, 0);
    lv_obj_set_y(ui_TempThresPanelSt, -60);
    lv_obj_set_align(ui_TempThresPanelSt, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempThresPanelSt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempThresPanelSt, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempThresPanelSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TempThresPanelSt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TempThresPanelSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TempThresPanelSt, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TempThresPanelSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_TempThresPanelSt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_TempThresPanelSt, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempThresImageSt = lv_image_create(ui_TempThresPanelSt);
    lv_image_set_src(ui_TempThresImageSt, &ui_img_temperature_png);
    lv_obj_set_width(ui_TempThresImageSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempThresImageSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempThresImageSt, -112);
    lv_obj_set_y(ui_TempThresImageSt, -1);
    lv_obj_set_align(ui_TempThresImageSt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempThresImageSt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TempThresImageSt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_TempThresImageSt, 100);

    ui_TempThresIncSt = lv_label_create(ui_TempThresPanelSt);
    lv_obj_set_width(ui_TempThresIncSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempThresIncSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempThresIncSt, -54);
    lv_obj_set_y(ui_TempThresIncSt, 0);
    lv_obj_set_align(ui_TempThresIncSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempThresIncSt, "[ + ]");
    lv_obj_set_style_text_color(ui_TempThresIncSt, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempThresIncSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TempThresIncSt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TempThresIncSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempThresIncSt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_TempThresIncSt, LV_OBJ_FLAG_CLICKABLE);

    ui_TempThresValSt = lv_label_create(ui_TempThresPanelSt);
    lv_obj_set_width(ui_TempThresValSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempThresValSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempThresValSt, 3);
    lv_obj_set_y(ui_TempThresValSt, 3);
    lv_obj_set_align(ui_TempThresValSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempThresValSt, "50.0");
    lv_obj_set_style_text_color(ui_TempThresValSt, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempThresValSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TempThresValSt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TempThresValSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempThresValSt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempThresDecSt = lv_label_create(ui_TempThresPanelSt);
    lv_obj_set_width(ui_TempThresDecSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempThresDecSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempThresDecSt, 72);
    lv_obj_set_y(ui_TempThresDecSt, 2);
    lv_obj_set_align(ui_TempThresDecSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempThresDecSt, "[ - ]");
    lv_obj_set_style_text_color(ui_TempThresDecSt, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempThresDecSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TempThresDecSt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TempThresDecSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempThresDecSt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_TempThresDecSt, LV_OBJ_FLAG_CLICKABLE);

    ui_HumThresPanelSt = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_HumThresPanelSt, 275);
    lv_obj_set_height(ui_HumThresPanelSt, 55);
    lv_obj_set_align(ui_HumThresPanelSt, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HumThresPanelSt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumThresPanelSt, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumThresPanelSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HumThresPanelSt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HumThresPanelSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HumThresPanelSt, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HumThresPanelSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_HumThresPanelSt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_HumThresPanelSt, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumThresImageSt = lv_image_create(ui_HumThresPanelSt);
    lv_image_set_src(ui_HumThresImageSt, &ui_img_humidity_png);
    lv_obj_set_width(ui_HumThresImageSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumThresImageSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumThresImageSt, -112);
    lv_obj_set_y(ui_HumThresImageSt, -1);
    lv_obj_set_align(ui_HumThresImageSt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumThresImageSt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_HumThresImageSt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_HumThresImageSt, 90);

    ui_HumThresIncSt = lv_label_create(ui_HumThresPanelSt);
    lv_obj_set_width(ui_HumThresIncSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumThresIncSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumThresIncSt, -54);
    lv_obj_set_y(ui_HumThresIncSt, 0);
    lv_obj_set_align(ui_HumThresIncSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumThresIncSt, "[ + ]");
    lv_obj_set_style_text_color(ui_HumThresIncSt, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumThresIncSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HumThresIncSt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HumThresIncSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumThresIncSt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_HumThresIncSt, LV_OBJ_FLAG_CLICKABLE);

    ui_HumThresValSt = lv_label_create(ui_HumThresPanelSt);
    lv_obj_set_width(ui_HumThresValSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumThresValSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumThresValSt, 4);
    lv_obj_set_y(ui_HumThresValSt, 3);
    lv_obj_set_align(ui_HumThresValSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumThresValSt, "50.0");
    lv_obj_set_style_text_color(ui_HumThresValSt, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumThresValSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HumThresValSt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HumThresValSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumThresValSt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumThresDecSt = lv_label_create(ui_HumThresPanelSt);
    lv_obj_set_width(ui_HumThresDecSt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumThresDecSt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumThresDecSt, 72);
    lv_obj_set_y(ui_HumThresDecSt, 2);
    lv_obj_set_align(ui_HumThresDecSt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumThresDecSt, "[ - ]");
    lv_obj_set_style_text_color(ui_HumThresDecSt, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumThresDecSt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HumThresDecSt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HumThresDecSt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumThresDecSt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_HumThresDecSt, LV_OBJ_FLAG_CLICKABLE);

    lv_obj_add_event_cb(ui_BottomNavDashboardSt, ui_event_BottomNavDashboardSt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BottomNavSensorSt, ui_event_BottomNavSensorSt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BottomNavRecordSt, ui_event_BottomNavRecordSt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SavePanelSt, ui_event_SavePanelSt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempThresIncSt, ui_event_TempThresIncSt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempThresDecSt, ui_event_TempThresDecSt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumThresIncSt, ui_event_HumThresIncSt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumThresDecSt, ui_event_HumThresDecSt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingPage, ui_event_SettingPage, LV_EVENT_ALL, NULL);
    uic_SettingPage = ui_SettingPage;
    uic_BottomNavSt = ui_BottomNavSt;
    uic_BottomNavDashboardSt = ui_BottomNavDashboardSt;
    uic_BottomNavSensorSt = ui_BottomNavSensorSt;
    uic_BottomNavRecordSt = ui_BottomNavRecordSt;
    uic_SavePanelSt = ui_SavePanelSt;
    uic_SaveImageSt = ui_SaveImageSt;
    uic_SaveLabelSt = ui_SaveLabelSt;
    uic_TempThresPanelSt = ui_TempThresPanelSt;
    uic_TempThresImageSt = ui_TempThresImageSt;
    uic_TempThresIncSt = ui_TempThresIncSt;
    uic_TempThresValSt = ui_TempThresValSt;
    uic_TempThresDecSt = ui_TempThresDecSt;
    uic_HumThresPanelSt = ui_HumThresPanelSt;
    uic_HumThresImageSt = ui_HumThresImageSt;
    uic_HumThresIncSt = ui_HumThresIncSt;
    uic_HumThresValSt = ui_HumThresValSt;
    uic_HumThresDecSt = ui_HumThresDecSt;

}

void ui_SettingPage_screen_destroy(void)
{
    if(ui_SettingPage) lv_obj_del(ui_SettingPage);

    // NULL screen variables
    uic_SettingPage = NULL;
    ui_SettingPage = NULL;
    ui_SettingLabelSt = NULL;
    uic_BottomNavSt = NULL;
    ui_BottomNavSt = NULL;
    uic_BottomNavDashboardSt = NULL;
    ui_BottomNavDashboardSt = NULL;
    uic_BottomNavSensorSt = NULL;
    ui_BottomNavSensorSt = NULL;
    uic_BottomNavRecordSt = NULL;
    ui_BottomNavRecordSt = NULL;
    ui_BottomNavSettingSt = NULL;
    uic_SavePanelSt = NULL;
    ui_SavePanelSt = NULL;
    uic_SaveImageSt = NULL;
    ui_SaveImageSt = NULL;
    uic_SaveLabelSt = NULL;
    ui_SaveLabelSt = NULL;
    uic_TempThresPanelSt = NULL;
    ui_TempThresPanelSt = NULL;
    uic_TempThresImageSt = NULL;
    ui_TempThresImageSt = NULL;
    uic_TempThresIncSt = NULL;
    ui_TempThresIncSt = NULL;
    uic_TempThresValSt = NULL;
    ui_TempThresValSt = NULL;
    uic_TempThresDecSt = NULL;
    ui_TempThresDecSt = NULL;
    uic_HumThresPanelSt = NULL;
    ui_HumThresPanelSt = NULL;
    uic_HumThresImageSt = NULL;
    ui_HumThresImageSt = NULL;
    uic_HumThresIncSt = NULL;
    ui_HumThresIncSt = NULL;
    uic_HumThresValSt = NULL;
    ui_HumThresValSt = NULL;
    uic_HumThresDecSt = NULL;
    ui_HumThresDecSt = NULL;

}
