// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_SettingPage;
lv_obj_t * ui_SettingPage = NULL;
lv_obj_t * ui_RecordLabelR1 = NULL;
lv_obj_t * ui_BottomNavR1 = NULL;
lv_obj_t * ui_BottomNavDashboardR1 = NULL;
lv_obj_t * ui_BottomNavSensorR1 = NULL;
lv_obj_t * ui_BottomNavRecordR1 = NULL;
lv_obj_t * ui_BottomNavSettingR1 = NULL;
lv_obj_t * ui_SavePanelS2 = NULL;
lv_obj_t * ui_SaveImageS2 = NULL;
lv_obj_t * ui_SaveLabelS2 = NULL;
lv_obj_t * ui_SavePanelS3 = NULL;
lv_obj_t * ui_SaveImageS3 = NULL;
lv_obj_t * ui_SaveLabelS3 = NULL;
lv_obj_t * ui_SaveS2 = NULL;
lv_obj_t * ui_SaveLabelS4 = NULL;
lv_obj_t * ui_SavePanelS1 = NULL;
lv_obj_t * ui_SaveImageS1 = NULL;
lv_obj_t * ui_SaveLabelS1 = NULL;
lv_obj_t * ui_SaveS1 = NULL;
lv_obj_t * ui_SaveLabelS5 = NULL;
// event funtions

// build funtions

void ui_SettingPage_screen_init(void)
{
    ui_SettingPage = lv_obj_create(NULL);
    lv_obj_add_flag(ui_SettingPage, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_SettingPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_SettingPage, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_SettingPage, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_bg_color(ui_SettingPage, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordLabelR1 = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_RecordLabelR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordLabelR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordLabelR1, -106);
    lv_obj_set_y(ui_RecordLabelR1, -101);
    lv_obj_set_align(ui_RecordLabelR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecordLabelR1, "SETTING");
    lv_obj_set_style_text_color(ui_RecordLabelR1, lv_color_hex(0xF8FAFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordLabelR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavR1 = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavR1, 334);
    lv_obj_set_height(ui_BottomNavR1, 50);
    lv_obj_set_x(ui_BottomNavR1, 2);
    lv_obj_set_y(ui_BottomNavR1, 113);
    lv_obj_set_align(ui_BottomNavR1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BottomNavR1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomNavR1, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomNavR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomNavR1, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomNavR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomNavR1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BottomNavR1, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavDashboardR1 = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavDashboardR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavDashboardR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavDashboardR1, -110);
    lv_obj_set_y(ui_BottomNavDashboardR1, 105);
    lv_obj_set_align(ui_BottomNavDashboardR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavDashboardR1, "HOME");
    lv_obj_set_style_text_color(ui_BottomNavDashboardR1, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavDashboardR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavDashboardR1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSensorR1 = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavSensorR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSensorR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSensorR1, -40);
    lv_obj_set_y(ui_BottomNavSensorR1, 105);
    lv_obj_set_align(ui_BottomNavSensorR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSensorR1, "SENSOR");
    lv_obj_set_style_text_color(ui_BottomNavSensorR1, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSensorR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSensorR1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavRecordR1 = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavRecordR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavRecordR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavRecordR1, 30);
    lv_obj_set_y(ui_BottomNavRecordR1, 105);
    lv_obj_set_align(ui_BottomNavRecordR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavRecordR1, "RECORD");
    lv_obj_set_style_text_color(ui_BottomNavRecordR1, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavRecordR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavRecordR1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomNavSettingR1 = lv_label_create(ui_SettingPage);
    lv_obj_set_width(ui_BottomNavSettingR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BottomNavSettingR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BottomNavSettingR1, 100);
    lv_obj_set_y(ui_BottomNavSettingR1, 105);
    lv_obj_set_align(ui_BottomNavSettingR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BottomNavSettingR1, "SETTING");
    lv_obj_set_style_text_color(ui_BottomNavSettingR1, lv_color_hex(0x08F334), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BottomNavSettingR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomNavSettingR1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SavePanelS2 = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_SavePanelS2, 275);
    lv_obj_set_height(ui_SavePanelS2, 35);
    lv_obj_set_x(ui_SavePanelS2, 0);
    lv_obj_set_y(ui_SavePanelS2, 55);
    lv_obj_set_align(ui_SavePanelS2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SavePanelS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SavePanelS2, lv_color_hex(0x2563EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavePanelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SavePanelS2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SavePanelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SavePanelS2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SavePanelS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SavePanelS2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SavePanelS2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveImageS2 = lv_image_create(ui_SavePanelS2);
    lv_image_set_src(ui_SaveImageS2, &ui_img_save_png);
    lv_obj_set_width(ui_SaveImageS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveImageS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveImageS2, -32);
    lv_obj_set_y(ui_SaveImageS2, 0);
    lv_obj_set_align(ui_SaveImageS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveImageS2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SaveImageS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SaveLabelS2 = lv_label_create(ui_SavePanelS2);
    lv_obj_set_width(ui_SaveLabelS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabelS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabelS2, 9);
    lv_obj_set_y(ui_SaveLabelS2, 1);
    lv_obj_set_align(ui_SaveLabelS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabelS2, "SAVE");
    lv_obj_set_style_text_color(ui_SaveLabelS2, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabelS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveLabelS2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveLabelS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveLabelS2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SavePanelS3 = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_SavePanelS3, 275);
    lv_obj_set_height(ui_SavePanelS3, 55);
    lv_obj_set_x(ui_SavePanelS3, 0);
    lv_obj_set_y(ui_SavePanelS3, -60);
    lv_obj_set_align(ui_SavePanelS3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SavePanelS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SavePanelS3, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavePanelS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SavePanelS3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SavePanelS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SavePanelS3, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SavePanelS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SavePanelS3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SavePanelS3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveImageS3 = lv_image_create(ui_SavePanelS3);
    lv_image_set_src(ui_SaveImageS3, &ui_img_temperature_png);
    lv_obj_set_width(ui_SaveImageS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveImageS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveImageS3, -112);
    lv_obj_set_y(ui_SaveImageS3, -1);
    lv_obj_set_align(ui_SaveImageS3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveImageS3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SaveImageS3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_SaveImageS3, 100);

    ui_SaveLabelS3 = lv_label_create(ui_SavePanelS3);
    lv_obj_set_width(ui_SaveLabelS3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabelS3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabelS3, -54);
    lv_obj_set_y(ui_SaveLabelS3, 0);
    lv_obj_set_align(ui_SaveLabelS3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabelS3, "[ + ]");
    lv_obj_set_style_text_color(ui_SaveLabelS3, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabelS3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveLabelS3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveLabelS3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveLabelS3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveS2 = lv_label_create(ui_SavePanelS3);
    lv_obj_set_width(ui_SaveS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveS2, 3);
    lv_obj_set_y(ui_SaveS2, 3);
    lv_obj_set_align(ui_SaveS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveS2, "50.0");
    lv_obj_set_style_text_color(ui_SaveS2, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveS2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveS2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveLabelS4 = lv_label_create(ui_SavePanelS3);
    lv_obj_set_width(ui_SaveLabelS4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabelS4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabelS4, 72);
    lv_obj_set_y(ui_SaveLabelS4, 2);
    lv_obj_set_align(ui_SaveLabelS4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabelS4, "[ - ]");
    lv_obj_set_style_text_color(ui_SaveLabelS4, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabelS4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveLabelS4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveLabelS4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveLabelS4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SavePanelS1 = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_SavePanelS1, 275);
    lv_obj_set_height(ui_SavePanelS1, 55);
    lv_obj_set_align(ui_SavePanelS1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SavePanelS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SavePanelS1, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SavePanelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SavePanelS1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SavePanelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SavePanelS1, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SavePanelS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SavePanelS1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SavePanelS1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveImageS1 = lv_image_create(ui_SavePanelS1);
    lv_image_set_src(ui_SaveImageS1, &ui_img_humidity_png);
    lv_obj_set_width(ui_SaveImageS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveImageS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveImageS1, -112);
    lv_obj_set_y(ui_SaveImageS1, -1);
    lv_obj_set_align(ui_SaveImageS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveImageS1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SaveImageS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_SaveImageS1, 90);

    ui_SaveLabelS1 = lv_label_create(ui_SavePanelS1);
    lv_obj_set_width(ui_SaveLabelS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabelS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabelS1, -54);
    lv_obj_set_y(ui_SaveLabelS1, 0);
    lv_obj_set_align(ui_SaveLabelS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabelS1, "[ + ]");
    lv_obj_set_style_text_color(ui_SaveLabelS1, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabelS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveLabelS1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveLabelS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveLabelS1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveS1 = lv_label_create(ui_SavePanelS1);
    lv_obj_set_width(ui_SaveS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveS1, 4);
    lv_obj_set_y(ui_SaveS1, 3);
    lv_obj_set_align(ui_SaveS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveS1, "50.0");
    lv_obj_set_style_text_color(ui_SaveS1, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveS1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveS1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveLabelS5 = lv_label_create(ui_SavePanelS1);
    lv_obj_set_width(ui_SaveLabelS5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabelS5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabelS5, 72);
    lv_obj_set_y(ui_SaveLabelS5, 2);
    lv_obj_set_align(ui_SaveLabelS5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabelS5, "[ - ]");
    lv_obj_set_style_text_color(ui_SaveLabelS5, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabelS5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveLabelS5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveLabelS5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveLabelS5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_SettingPage = ui_SettingPage;

}

void ui_SettingPage_screen_destroy(void)
{
    if(ui_SettingPage) lv_obj_del(ui_SettingPage);

    // NULL screen variables
    uic_SettingPage = NULL;
    ui_SettingPage = NULL;
    ui_RecordLabelR1 = NULL;
    ui_BottomNavR1 = NULL;
    ui_BottomNavDashboardR1 = NULL;
    ui_BottomNavSensorR1 = NULL;
    ui_BottomNavRecordR1 = NULL;
    ui_BottomNavSettingR1 = NULL;
    ui_SavePanelS2 = NULL;
    ui_SaveImageS2 = NULL;
    ui_SaveLabelS2 = NULL;
    ui_SavePanelS3 = NULL;
    ui_SaveImageS3 = NULL;
    ui_SaveLabelS3 = NULL;
    ui_SaveS2 = NULL;
    ui_SaveLabelS4 = NULL;
    ui_SavePanelS1 = NULL;
    ui_SaveImageS1 = NULL;
    ui_SaveLabelS1 = NULL;
    ui_SaveS1 = NULL;
    ui_SaveLabelS5 = NULL;

}
