// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SETTINGPAGE_H
#define UI_SETTINGPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingPage
extern void ui_SettingPage_screen_init(void);
extern void ui_SettingPage_screen_destroy(void);
extern lv_obj_t * ui_SettingPage;
extern lv_obj_t * ui_RecordLabelR1;
extern lv_obj_t * ui_BottomNavR1;
extern lv_obj_t * ui_BottomNavDashboardR1;
extern lv_obj_t * ui_BottomNavSensorR1;
extern lv_obj_t * ui_BottomNavRecordR1;
extern lv_obj_t * ui_BottomNavSettingR1;
extern lv_obj_t * ui_SavePanelS2;
extern lv_obj_t * ui_SaveImageS2;
extern lv_obj_t * ui_SaveLabelS2;
extern lv_obj_t * ui_SavePanelS3;
extern lv_obj_t * ui_SaveImageS3;
extern lv_obj_t * ui_SaveLabelS3;
extern lv_obj_t * ui_SaveS2;
extern lv_obj_t * ui_SaveLabelS4;
extern lv_obj_t * ui_SavePanelS1;
extern lv_obj_t * ui_SaveImageS1;
extern lv_obj_t * ui_SaveLabelS1;
extern lv_obj_t * ui_SaveS1;
extern lv_obj_t * ui_SaveLabelS5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SettingPage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

