// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SENSORPAGE_H
#define UI_SENSORPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorPage
extern void ui_SensorPage_screen_init(void);
extern void ui_SensorPage_screen_destroy(void);
extern void ui_event_SensorPage(lv_event_t * e);
extern lv_obj_t * ui_SensorPage;
extern lv_obj_t * ui_SensorLabelS;
extern lv_obj_t * ui_TemperaturePanelS;
extern lv_obj_t * ui_TemperatureLabelS;
extern lv_obj_t * ui_TemperatureImageS;
extern lv_obj_t * ui_TemperatureS;
extern lv_obj_t * ui_TemperatureUnitLabelS;
extern lv_obj_t * ui_HumidityPanelS;
extern lv_obj_t * ui_HumidityLabelS;
extern lv_obj_t * ui_HumidityImageS;
extern lv_obj_t * ui_HumidityS;
extern lv_obj_t * ui_HumidityUnitLabelS;
extern lv_obj_t * ui_IntensityPanelS;
extern lv_obj_t * ui_IntensityLabelS;
extern lv_obj_t * ui_IntensityImageS;
extern lv_obj_t * ui_IntensityS;
extern lv_obj_t * ui_IntensityUnitS;
extern lv_obj_t * ui_SavePanelS;
extern lv_obj_t * ui_SaveImageS;
extern lv_obj_t * ui_SaveLabelS;
extern lv_obj_t * ui_SaveS;
extern lv_obj_t * ui_SaveTotalLabelS;
extern lv_obj_t * ui_BottomNavS;
extern void ui_event_BottomNavDashboardS(lv_event_t * e);
extern lv_obj_t * ui_BottomNavDashboardS;
extern lv_obj_t * ui_BottomNavSensorS;
extern void ui_event_BottomNavRecordS(lv_event_t * e);
extern lv_obj_t * ui_BottomNavRecordS;
extern void ui_event_BottomNavSettingS(lv_event_t * e);
extern lv_obj_t * ui_BottomNavSettingS;
extern void ui_event_ErrorPanelS(lv_event_t * e);
extern lv_obj_t * ui_ErrorPanelS;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ErrorModalS;
extern void ui_event_ErrorOKBtnS(lv_event_t * e);
extern lv_obj_t * ui_ErrorOKBtnS;
extern lv_obj_t * ui_ErrorOKLabelS;
extern lv_obj_t * ui_ErrorPanelTopS;
extern lv_obj_t * ui_ErrorLabelS;
extern lv_obj_t * ui_ErrorLabel1S;
extern lv_obj_t * ui_ErrorLabel2S;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SensorPage;
extern lv_obj_t * uic_SensorLabelS;
extern lv_obj_t * uic_TemperaturePanelS;
extern lv_obj_t * uic_TemperatureLabelS;
extern lv_obj_t * uic_TemperatureImageS;
extern lv_obj_t * uic_TemperatureS;
extern lv_obj_t * uic_TemperatureUnitLabelS;
extern lv_obj_t * uic_HumidityPanelS;
extern lv_obj_t * uic_HumidityLabelS;
extern lv_obj_t * uic_HumidityImageS;
extern lv_obj_t * uic_HumidityS;
extern lv_obj_t * uic_HumidityUnitLabelS;
extern lv_obj_t * uic_IntensityPanelS;
extern lv_obj_t * uic_IntensityImageS;
extern lv_obj_t * uic_IntensityS;
extern lv_obj_t * uic_IntensityUnitS;
extern lv_obj_t * uic_SavePanelS;
extern lv_obj_t * uic_SaveImageS;
extern lv_obj_t * uic_SaveLabelS;
extern lv_obj_t * uic_SaveS;
extern lv_obj_t * uic_BottomNavS;
extern lv_obj_t * uic_BottomNavDashboardS;
extern lv_obj_t * uic_BottomNavSensorS;
extern lv_obj_t * uic_BottomNavRecordS;
extern lv_obj_t * uic_BottomNavSettingS;
extern lv_obj_t * uic_ErrorPanelS;
extern lv_obj_t * uic_ErrorModalS;
extern lv_obj_t * uic_ErrorOKBtnS;
extern lv_obj_t * uic_ErrorOKLabelS;
extern lv_obj_t * uic_ErrorPanelTopS;
extern lv_obj_t * uic_ErrorLabelS;
extern lv_obj_t * uic_ErrorLabel1S;
extern lv_obj_t * uic_ErrorLabel2S;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

