// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SETTINGPAGE_H
#define UI_SETTINGPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingPage
extern void ui_SettingPage_screen_init(void);
extern void ui_SettingPage_screen_destroy(void);
extern void ui_event_SettingPage(lv_event_t * e);
extern lv_obj_t * ui_SettingPage;
extern lv_obj_t * ui_SettingLabelSt;
extern lv_obj_t * ui_BottomNavSt;
extern void ui_event_BottomNavDashboardSt(lv_event_t * e);
extern lv_obj_t * ui_BottomNavDashboardSt;
extern void ui_event_BottomNavSensorSt(lv_event_t * e);
extern lv_obj_t * ui_BottomNavSensorSt;
extern void ui_event_BottomNavRecordSt(lv_event_t * e);
extern lv_obj_t * ui_BottomNavRecordSt;
extern lv_obj_t * ui_BottomNavSettingSt;
extern void ui_event_SavePanelSt(lv_event_t * e);
extern lv_obj_t * ui_SavePanelSt;
extern lv_obj_t * ui_SaveImageSt;
extern lv_obj_t * ui_SaveLabelSt;
extern lv_obj_t * ui_TempThresPanelSt;
extern lv_obj_t * ui_TempThresImageSt;
extern void ui_event_TempThresIncSt(lv_event_t * e);
extern lv_obj_t * ui_TempThresIncSt;
extern lv_obj_t * ui_TempThresValSt;
extern void ui_event_TempThresDecSt(lv_event_t * e);
extern lv_obj_t * ui_TempThresDecSt;
extern lv_obj_t * ui_HumThresPanelSt;
extern lv_obj_t * ui_HumThresImageSt;
extern void ui_event_HumThresIncSt(lv_event_t * e);
extern lv_obj_t * ui_HumThresIncSt;
extern lv_obj_t * ui_HumThresValSt;
extern void ui_event_HumThresDecSt(lv_event_t * e);
extern lv_obj_t * ui_HumThresDecSt;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SettingPage;
extern lv_obj_t * uic_BottomNavSt;
extern lv_obj_t * uic_BottomNavDashboardSt;
extern lv_obj_t * uic_BottomNavSensorSt;
extern lv_obj_t * uic_BottomNavRecordSt;
extern lv_obj_t * uic_SavePanelSt;
extern lv_obj_t * uic_SaveImageSt;
extern lv_obj_t * uic_SaveLabelSt;
extern lv_obj_t * uic_TempThresPanelSt;
extern lv_obj_t * uic_TempThresImageSt;
extern lv_obj_t * uic_TempThresIncSt;
extern lv_obj_t * uic_TempThresValSt;
extern lv_obj_t * uic_TempThresDecSt;
extern lv_obj_t * uic_HumThresPanelSt;
extern lv_obj_t * uic_HumThresImageSt;
extern lv_obj_t * uic_HumThresIncSt;
extern lv_obj_t * uic_HumThresValSt;
extern lv_obj_t * uic_HumThresDecSt;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

